== To the Reader

Friendly Reader,
It seems unnecessary for me to say more than to hint at some
particular qualifications and eminent services of the author,
with the end of publishing his works,
there being sundry following accounts and
testimonies of faithful brethren concerning him,
not only of this nation of Ireland,
wherein he resided and travelled much in the work of the Gospel,
but also from Great Britain, which he often visited; and likewise from America,
where he had been twice.
To which accounts, together with his journal, thou art referred;
in the serious perusal whereof it will appear
that he had the gift of an apostle of Christ,
approving himself as such in his powerful, effectual ministry, and care of the churches,
and in much patience in afflictions, in watching, fasting, hard travels,
and perils by sea and land, in the wilderness, and also by false brethren,
following his heavenly captain through many tribulations,
preaching the Gospel of the kingdom of God freely;
not expecting a reward from any mortal man.
Having on the holy armour, and weapons, not carnal, but mighty through God; he,
as a good soldier of Jesus Christ, was made valiant and skillful,
to war against the prince and power of darkness, profanity,
and spiritual wickedness in high places, to the bringing down strong holds of Satan,
and instrumental in turning many to righteousness, who became as seals of his ministry;
and having overcome by the blood of the Lamb, and by the word of his testimony,
I doubt not is now possessing a never-fading crown of glory.

The memory of the just is pronounced blessed. Proverbs 10:7.
And it has been the practice of the righteous, as examples to posterity,
to record a memorial of the works off good men, in the holy Scriptures, which,
by the wonderful providence and mercy of God,
have been preserved through many dark ages of the world, and transmitted to us,
as a cloud of witnesses, to the great comfort of the godly;
the serious perusal whereof is earnestly recommended to both old and young.

For the like purpose is an account of the labours,
etc. of this our late worthy friend collected, as fragments that should not be lost,
and that thou, reader, mayest thereby be encouraged in diligently serving God,
according to the measure of grace bestowed on thee through Jesus Christ our Saviour,
without whom we can do nothing; and so have cause of rejoicing at thy latter end,
in feeling great peace from the Lord flow in thy soul,
as had this our friend in the evening of his day,
and obtain a crown of righteousness hereafter in the heavenly kingdom,
which is the sincere desire of thy friend, who wisheth salvation to all mankind.

[.signed-section-signature]
John Stoddart
