[#epistles, short="Epistles by Thomas Wilson and James Dickenson"]
== Epistles Written by Thomas Wilson, And His Fellow-Labourer in the Service of the Gospel, James Dickinson, Whilst in America.

[.chapter-subtitle--blurb]
An Epistle to Friends in Virginia and Carolina, from King`'s creek, in Maryland,
the 12th of the Second month, 1692.

[.salutation]
Dear Friends,

All dwell in the love of God, by which your hearts were at first reached,
and tender desires raised, to make your peace with him, which was lost by reason of sin.
It was the love of the Father to bring you to his Son, the Lord Jesus Christ,
in whom you all have life and salvation, as you abide in him, and keep in his love,
that draws your affections heavenward, where they will be fixed on heavenly things,
and where your souls will witness the sweetness of life,
strengthening and building you up in that most holy faith,
which God hath called you into, and made you partakers of.
Every one be careful to walk worthy of the vocation, whereunto ye are called,
in all fear and meekness, watching in the light,
where you will discern the wiles of the enemy in
all his cunning baits and transformations.
As every one of you keeps inward to the Lord, you will have salt in yourselves,
to savour withal, as Christ our Lord said, "`Everyone shall be salted with fire,
and every sacrifice seasoned with salt; have salt in yourselves,
and dwell at peace one with another.`"

As every one keeps to the spirit of judgment and burning,
and knows the fire of God`'s jealousy kindled against every appearance of evil,
you will be kept inquiring and taking counsel of the Lord, where you will be safe,
and can do nothing against the truth, but for the truth,
and the Lord will take delight to appear in your meetings, by his living power,
and give you a sense and feeling beyond words, as he hath done unto a remnant of you.
Blessed be his holy name forever,
that there are those who can taste words as the mouth tastes meat;
therefore is it that words cannot deceive such, but all have not attained this length;
some are unskilful, and have need of milk, which our God will give.

If you keep those longing desires that are already raised in you,
ye shall know the sincere milk of the word that you may grow thereby,
from one degree of grace unto another, until you become perfect men in Christ Jesus,
in whom you may edify and build up one another in the most holy faith,
by which you will be made heirs of that crown which is incorruptible, and full of glory.
For the attainment of this, let every one press forward, in the life of righteousness,
watching one over another for good, and stirring up one another to love and good works,
wherein God will supply you with the increase of his holy Spirit,
by which you will be fitted for the service God hath called you into,
which is to be zealous for the truth upon earth,
and against everything that would cause the truth to be evil spoken of,
that none may be as those spoken of formerly,
who walked as enemies to the cross of Christ,
and were a grief to the faithful in ages past.
Such are a grief to the honest-hearted in this day,
who are concerned for God and his truth, and for the spread of the Gospel,
travelling for the prosperity of Zion, and peace of Jerusalem,
and know her to be a quiet habitation, and themselves inhabitants thereof.
The Lord is making these as watchmen upon her walls, whose resolution is to keep them up,
notwithstanding the scoffs and reproaches of such, who, like Sanballat and Tobias,
are without the city.
Those who are within, are really concerned for God,
and to stand against every appearance of evil, both in themselves and others;
and the Lord is enduing them with power and wisdom proceeding from his holy Spirit,
that they heed not the reproaches of Ammon, nor the reviling of Moab;
for though "`he may go into the sanctuary to pray, he shall not prevail, but Israel,
that wrestleth with the Lord, shall prevail.`"

Therefore let your care be, to wait for the assistance of God`'s spirit,
and that none plead for the truth, and be out of the Spirit of Truth,
for that will never tend to God`'s glory, nor your edification; but on the contrary,
to darken, veil, and oppress the Seed of God, one in another.
But as all keep low in their respective gifts,
waiting to know the assistance of God`'s spirit, being nothing without it,
you will feel the Lord to work all your works in you and for you,
and give power to answer what he requires of you,
and then his love will be increased into you, and you will abide in favour with him;
as you are preserved here, you will daily witness an increase of the life of truth,
which will occasion praises to be sounded forth to the Lord God and the Lamb,
who is blessed forevermore.
Amen.

[.offset]
Postscript:

Dear Friends, we desire you, in the love of God,
as it was our advice when present with you, that you watch one over another in love,
and keep in a Christian spirit, forgiving one another;
if any brother have anything against another, as God, for Christ`'s sake,
doth forgive you, so forgive one another.
Take the advice of the apostle, "`Be not children in understanding,
but in malice be ye children,`" that you may bear the marks of true disciples,
and manifest yourselves to all men to be such;
that you may be preachers of righteousness to the world, that lies in wickedness,
and follow after those things that make for peace, and eschew the contrary,
and the God of peace will bless you, and keep you from evil, that it hurt you not,
to his glory, and your comfort.
Amen.

Let copies of this be taken and read in your meetings, and a copy be sent to Carolina.
So remain your friends and brethren in the truth, letting you know that we are well,
with love to you all, sending these lines as a token thereof.
Farewell.

[.signed-section-signature]
Thomas Wilson, James Dickinson

[.blurb]
=== An Epistle to Friends in Pennsylvania.

[.salutation]
Dear Friends,

The tender salutation of our love in the Lord Jesus Christ,
salutes you all, in the spring of divine love, as those that desire your growth,
and settlement in God`'s everlasting truth, of which, in his rich mercy,
he hath made you sensible, and gathered you into,
wherein you have found great peace with God, and sweet unity one with another,
so that your hearts have been filled in your assemblies with his living presence,
which hath occasioned praises to spring unanimously unto the Lord.

Dear Friends, truth is the same that ever it was,
and the power of it as prevailing as ever; and where it is kept to, and dwelt in,
hath the same effect as ever, as many of you are witnesses,
who keep your habitation therein,
with whom our souls are bound up in God`'s everlasting covenant of light, in which,
as we walk, we have true fellowship one with another,
and the blood of Jesus Christ his Son, cleanseth us from all unrighteousness.
Let all be careful to walk in the light, where there is no occasion of stumbling,
but every one will see their way in the Lord,
and where your fellowship will be increased with him, and one with another,
and you will bear to the world the marks of true disciples, if ye love one another;
for God is love, and they that dwell in him, dwell in love.
"`He that saith he is in the light, and hateth his brother, is in darkness,
even until now.
For if a man say he loves God, and hateth his brother, he is a liar.`"

Therefore we desire you may follow those things that make for peace,
and eschew the contrary, all keeping down to your own gifts, travelling with the Seed,
and for the coming of it into dominion, in all your hearts,
that you may know your wills truly subjected to the will of God.
Here you will be kept in a holy dread and pure awe, in all your meetings,
and in your lives and conversations will be preachers of righteousness,
tender of God`'s glory, and one over another, watching for good, and none for evil;
but that eye will be plucked out.
As you are kept truly bow`'ed down,
still waiting to feel the operation of the power of God,
that was before the power of the devil, you will feel the arm that gathered you,
to be about you, and keep you in all trials and exercises,
as many have done to God`'s glory and their comfort; so that they can say,
the same arm which gathered them, hath kept them unto this day, in unity with the Lord,
and in fellowship one with another,
and are concerned to be kept in the unity of the spirit, which is the bond of peace.
Those grow sound in the faith, and in charity, and know the virtues of the charity,
that "`seeks not her own, is not easily provoked, thinketh no evil,
rejoiceth not in iniquity, but rejoiceth in the truth;`" without which,
the apostle concluded, he was but as sounding brass and a tinkling symbal,
though he had never so large gifts without it.

Dear Friends, what gifts soever you have received, be careful that you be improving them,
to the honour of the Giver, as those that know an account must be given unto Him,
who will require it of us all; and how near that time is to any,
may be out of the sight of most of us.

Our souls are concerned for you, that you may all grow in grace,
and increase in the knowledge of our Lord Jesus Christ, and in obedience unto him,
for it is they that do his will, that shall know of his doctrine;
whose doctrine is known to drop as the dew, and his speech to distill as the small rain.
Blessed be his name forever,
he is daily opening the divine mysteries of his kingdom
to them who are kept humble and low before him,
truly desiring to keep at wisdom`'s gate, and wait for counsel from the Lord every day,
and to feel the assistance of his spirit, and dare not move until the Lord go before,
and draw them forward; these walk safely, and feel their peace to flow as a river.
The Lord establisheth their goings,
that they are not easily moved with any storm or wind, but know the rock,
and are as the dove that maketh her nest there; and though such may be tried,
and lie as amongst the pots, yet shall they come forth more bright,
as the dove whose wings are covered with silver, and her feathers with yellow gold,
and shall know the trial of their faith to be
more precious than that of gold which perisheth.

So all keep the word of God`'s patience,
and wait for the feeling of his power in all your meetings,
that your hearts may be kept tender;
and a godly care will be more and more raised in you all, to watch over your children,
and train them up in the fear of the Lord,
and to discharge your duty in restraining them,
out of the ways and fashions of the world.
Our souls are concerned for your tender children, that as they grow in years,
they may grow in grace, and be God`'s children,
succeeding you in the way of righteousness, and be a blessing to you in your old age.
We are sensible God`'s great love is unto them,
and several of them were reached by his power, when we were with you;
our love flows unto you and them,
that you all may be kept by the power of God out of evil,
in that life wherein you may find acceptance with him,
where the streams of his love will be daily opened unto you,
and in the sense of it you will be engaged to walk in fear before him,
as those that feel his preserving arm, to be with and to support you.
That God of his infinite mercy may grant this for you all,
is the sincere breathing of your friends and brethren, in the kingdom, patience,
and tribulation of the Lamb, with hearts full of love unto all the faithful,
desiring your prayers to God for us, unto whom we commit you, with our own souls,
who is only able to keep us from falling; to whom be.
all fear, obedience and worship, both now and evermore.
Amen.

[.signed-section-signature]
Thomas Wilson, James Dickinson

[.signed-section-context-close]
From Rhode Island, the 5th of the Fifth month, 1692.

[.blurb]
=== An Epistle to Friends in Barbados and Elsewhere.

[.salutation]
Dear Friends, brethren and sisters.

For whom we are concerned in true brotherly love, wherewith God,
in his rich mercy hath filled our hearts, unto all the sons and daughters of men,
but more especially to the household of faith,
which hath been gathered by his eternal power,
the salutation of our love in the Lord Jesus Christ tenderly flows forth.
We desire you all to keep down to your gifts which God hath given you,
waiting low in his fear, to feel the operation of his living power,
to tender all your hearts, and open them unto the Lord,
that your spirits may be truly bowed and subjected unto God`'s will,
which is your sanctification.
Here the springs of God`'s love will flow, and his life run from vessel to vessel,
and the life of innocency flourish amongst you,
and the Lord will put his own comeliness upon you, and cover you with his spirit,
and your delight will be to feel the overshadowing of his presence.
Here self will be had in no reputation, but denied by all,
and your delight will be under the cross, which is the power of God,
whereby you will be crucified to the world, and the world unto you;
so will the Lord delight to visit your assemblies with his living presence,
and fill your hearts with love to himself, and one to another,
whereby you will be kept tender and humble, watching one over another for good,
and none for evil; that eye that watches for evil must be plucked out,
for wherever it is, it doth offend.

All give up your hearts to God, to be kept by his power, in fellowship with him;
then will your fellowship be sweet one with another,
being made partakers of the saints fellowship, who wrote one to another,
that they might have sweet fellowship together, and their fellowship was with the Father,
and with his Son, Christ Jesus.
So will you know all things that offend to be cast out of the kingdom,
and you will be tender one over another, the strong lending a hand of help to the weak,
and be of Moses`' mind, who wished that all the people were prophets,
and would not leave a hoof behind in Egypt; and not of the mind of him,
that would have had Moses forbid Eldad and Medad to prophesy in the camp;
nor of the mind of Pharaoh, and the Egyptians,
that would have only the men to go and sacrifice to the Lord,
but the women and children to stay and not go to sacrifice.
Moses wished that all the Lord`'s people were prophets,
and that he would put his spirit upon them, and the women and children all must go;
and it is the mind of Christ, our spiritual Moses, that all, both male and female,
should come up in their places.
Jacob was tender and careful, not to over drive the flock,
lest those with young should be hurt; which ought to be a caution to us,
and thereby learn us to keep to the Lord`'s spirit.
Wait for wisdom from him, that you may be guided thereby,
in your gifts and places in the church of Christ,
and so build up one another in the most holy faith,
stirring up one another to love and good works,
that wisdom may be justified of her children, and "`your lights shine before men,
that they seeing your good works, may glorify your Father which is in heaven.`"
Be ye as a city set upon a hill, where their elder men will grow sound in the faith,
and in charity, teaching the younger men to be sober-mhided,
and likewise the "`aged women, that they be in behaviour as becometh holiness;
not false accusers, but teachers of good things,
that they may teach the younger women to be sober, to love their husbands,
to love their children, to be chaste, keepers at home,
that the word of God be not blasphemed,
and that their adorning should not be the outward adorning of plaiting the hair,
and wearing of gold, or putting on of apparel;
but let it be of the hidden man of the heart, in that which is not corruptible,
even the ornament of a meek and quiet spirit,
which in the sight of God is of great price,
for after this manner the holy women of old adorned themselves, who trusted in God.`"
All that keep to God`'s spirit, must mind those things,
and labour to keep their children out of pride,
and the foolish fashions that are in the world, which youth are apt to run into,
and covet after, and to take liberty one by another.

You that are parents of children, take Abraham for an example,
of whom God gave testimony that he would command his household after him;
so all are to wait for power from God, and stand in your authority in your families;
and not indulge your children when they are young,
nor deck them in the fashions of the world, as soon as they can go,
nor let them speak the language of the world, as soon as they can speak,
without reproving them, nor let them keep company with the world,
without restraining them.
These things we have seen to our great grief,
and they have brought bitter mourning to our souls,
considering the floodgate of iniquity it opens to youth.

As those who feel a concern upon our spirits for the truth, and your good,
and your childrens`' also, we are drawn forth in tender love,
to desire you to mind the truth, and the power of it, and be taught by it,
and then we know you will be concerned to see things amended, where they have been amiss.
We know there are many under a concern with our souls in this matter,
which has been weighty upon our spirits; and therefore in true love,
we visit you with these lines,
desiring the Lord may fill you with love and zeal for his name and truth;
that you may be valiant for it upon the earth, and in your testimonies for God,
and against all that would defile the camp of God, and bring his wrath upon us,
or cause him to withdraw his holy presence from us, which hath given us life,
and separated us from the world`'s ways, worships, customs, and fashions.
Now, as God hath separated us, we are to keep to him, that he may keep us so separated,
that we may never join with those things again.
For if we do so join, we shall incur his displeasure, as Israel did,
when they joined themselves with the inhabitants of the land,
which the Lord had commanded they should not do, and brought God`'s wrath upon them,
whereby we may take warning not to commit the like evil
in suffering our minds to wander from the Lord,
and join with the world in their ways, worships, customs and fashions,
or to marry with them, which was expressly forbidden in the time of the first covenant,
and also by the apostle in the second covenant, who said,
"`Be not unequally yoked with unbelievers,`" etc.
So thus you may see that God`'s people were to dwell alone,
and not to mix with other nations; and while they did so dwell,
the Lord wonderfully blessed them, so that Balaam could not curse them,
nor any enchantment prevail against them,
but their strength was as the strength of a lion and a unicorn,
and their enemies were a prey to them.
But when they joined themselves unto Baalpeor, the Lord`'s wrath was kindled against them,
so that twenty-three thousand died of the plague, which the Lord sent amongst them.

Oh! that your zeal may appear in a Gospel way, as Phineas did,
according to that legal covenant, to the appeasing God`'s anger,
that ye may know the Lord to make his covenant of peace with you,
and that it may abide with you forever.
For truly, God is jealous of his own glory,
and will have a clean people to serve him in sincerity and uprightness,
clear of all mixtures, and linsey-woolsey garments,
which are not to be worn in this Gospel day,
wherein the Lord hath been great in mercy and love, causing his glorious light to shine,
and giving us the knowledge of himself; therefore let our care be, to keep in his fear,
that we may walk before him in humility, worthy of those mercies and blessings,
that God in all things may be glorified, and our peace preserved with him.
Amen.

[.signed-section-closing]
We remain your friends and brethren in the truth,

[.signed-section-signature]
Thomas Wilson, James Dickinson

[.signed-section-context-close]
From Antigua, the 14th of the Tenth month, 1692.

[.blurb]
=== An Epistle to Friends in Philadelphia

[.salutation]
Dear Friends,

Our dear love in the holy truth, tenderly salutes you all.
We received a letter from New York, and were glad to hear of your welfare,
and the Lord`'s appearance amongst you, in your general meeting,
and prevailing by his presence and power upon your spirits, tendering them before him,
a state which was never rejected of him.

The God of our life keep you all an inward people,
that the weight of his power may be upon your souls,
that you may learn in true silence and stillness,
where the divine mysteries of his kingdom are daily opened,
and you will see through the mystery of iniquity,
and not be ignorant of the wiles of Satan; but abiding in the light,
they will be clearly discovered, and you will be pressing after the life of innocency,
whereunto God hath called you, and which must wear the crown.
They who are most in favour with him, make it their habitation,
labouring to have their own spirits silenced, and daily depend upon God`'s teaching.

It was our glory in years past to learn in silence,
which is since too much neglected by many professors of truth,
upon whom a light frothy spirit has prevailed, having a life in disputes, arguments,
and words to little purpose, but amusing and perverting the mind,
which ought to be stayed upon God, who is the strength and stay of his people,
keeping them in perfect peace, whose minds are stayed upon him.
Such who run into disputes in their own wills and imaginations, depart from the truth,
the sure foundation, and the light, whereunto our minds were at first turned,
in which all that walk, are preserved in sweet fellowship one with another,
and their unity in the spirit and light of the Lord Jesus Christ increaseth with him,
and one with another, being weighty in spirit, not easily moved.
Such see that all the disputes and arguments, even concerning religious matters,
which proceed from the will of man, not of God`'s spirit, are but as froth and chaff,
that will not abide God`'s fan, but be blown away by the whirlwind of his wrath.

All your safety is and will be, to keep inward to the Lord, that he may be your teacher,
your own spirits being silenced, waiting with delight to hear what he speaks.
Then if he be pleased to open any of your mouths, for the edification one of another,
it will be in his power and wisdom from above, that is, first pure, then peaceable,
gentle, and easy to be entreated,
in which you may build up one another in the most holy faith;
but those that run into a passionate, hasty spirit,
go out of the wisdom which is from above, into that which is from below,
and the wrath of man cannot work the righteousness of God.

So all keep in your own gifts, inward to the Lord, who will fit you for his service,
and guide you in bis wisdom, to hit the mark aimed at,
and preserve you in the living faith delivered unto you,
of which Christ Jesus our Lord is the Author, whereby you may live,
as did the just in every generation, to the glory of God, and being, by his power,
made as the weighty wheat, be gathered into the garner of his salvation,
when those who run out, with frothy notions of their own imaginations, will be as chaff,
or dead men before the Lord.

Our souls have been often concerned for you, in these parts of the world,
that you may be kept by the power of God, unto whom we leave you,
desiring your prayers for our preservation in the holy truth,
wherein we remain your friends and brethren,

[.signed-section-signature]
Thomas Wilson, James Dickinson

[.signed-section-context-close]
Nevis, the 4th of the Twelfth month, 1692-3.

[.blurb]
=== Another Epistle to Friends in America.

[.salutation]
Dear Friends,

Our tender love in the Lord Jesus Christ, dearly salutes you,
and all the faithful in that island,
amongst whom we have travelled to preach the Gospel of life and salvation,
desiring the Lord may bless you all, and increase his love amongst you,
and that you may be kept in his holy covenant of peace, into which he hath gathered you,
by his own power, where you have sweet communion with the Lord, and one with another.
In this you are a true strength one to another,
the sweetness whereof none know but those who dwell in it,
and keep to the conduct of the power that gathered them.
These daily feel the springs of divine love and life, opened unto them,
which keep them alive to God, and under a true concern for the peace of the church,
and prosperity of Zion.
We desire that this care may be kept in by you all,
whom God hath gathered to abide in his covenant of light and life, and walk therein,
where you will have true fellowship,
and know the blood of Jesus Christ to cleanse you from all sin and unrighteousness,
which hath been and still is the occasion of all the strife and contention,
rents and divisions that have happened amongst us since we have been a people.
We pray God to put a stop to all these,
and keep all his people in true fear and humility in their gifts,
waiting to know their strength renewed in him, that they may stand against the enemy,
who labours to scatter God`'s heritage, whom he hath gathered.
So be preserved in unity with the Lord, and one with another,
where cries and supplications are daily poured forth to the Lord for one another,
as ours are for you, and we desire yours may be for us,
that we may be borne up through the many tribulations we meet with,
and that we may have the gift of utterance to proclaim the everlasting Gospel,
and be preserved out of the hands of unreasonable men.

Dear Friends, we desire as you are free and clear, and have your hearts open thereto,
that you will send us a certificate from your Monthly Meeting of your unity with us,
while we were present with you, and at our parting from you; and enclose it for us,
to be left at Joseph Groves`' in Barbados.
We have had good service here, and the Lord hath been with us, to our great comfort,
though under great sorrow of soul, for those things which have happened at Delaware,
and more especially to see them published in print, to the view of the world,
and the enemies of truth.
The publishers of which may expect a reward according to their works, and God,
in his own time, will wipe away all those reproaches,
and ease the spirits of them that travel under the weight thereof.
Unto him we are willing to commit the cause, and do commit you, and our own souls;
so remain your friends and brethren,

[.signed-section-signature]
Thomas Wilson, James Dickinson

[.blurb]
=== To Friends of Mount-melick, Men`'s Meeting, and Elsewhere.

[.salutation]
Dear Friends,

I have been for some years past, and more especially of late,
under deep considerations respecting the state of Friends,
and the affairs of truth in general, and our Monthly Meeting in particular,
which hath brought a weight of exercise upon my mind;
and doubting whether I may ever have an opportunity of seeing you,
so as to ease myself of what remains as a concern upon me,
I was willing to communicate these k\w lines to your weighty and serious consideration.

The order and government of the church was settled by the same divine spirit,
from which the true ministry sprung; and all who speak in Men`'s Meetings,
should be careful they do not speak anything to offend God,
but wait to have their offerings seasoned with grace,
and offered in the same divine spirit,
by which the order and government of the church was first established.
And as the doctrine of our Lord and Saviour Jesus Christ directed,
that every one is to be salted with fire, and every sacrifice seasoned with salt; mark,
the vessel is to be seasoned with the holy fire of the word of God,
and sanctified by the truth, otherwise God will not accept of their offerings,
no more than he did the offerings of Aaron`'s sons, who offered strange fire,
which the Lord never commanded, and so brought death upon them.
You may also observe, that when Moses was dead, who received the law from God`'s mouth,
that Joshua was to succeed him in the same spirit,
which plainly appears from the positive command of the Lord to him,
that he should be courageous, and observe and do according to all the law, which Moses,
the servant of the Lord commanded him.
He was not to depart therefrom either to the right hand or to the left,
that so he might prosper wherever he went.
By which it is plain, the blessing is only to them, who come up in the same holy Spirit,
which case is very applicable to Friends in this our day; for it is undeniable,
that the weighty rules and order of the church were received in the beginning by
our ancients and elders from the opening of the divine Spirit of Truth,
and settled in the counsel of God.
And as surely as ever Joshua was to succeed Moses,
and to observe all the law which was commanded him; so are Friends now,
who are of a succeeding generation,
faithfully to keep and observe those weighty
rules and precepts left them by their elders,
without turning from them, either to the right hand or to the left;
and it remains as a testimony in my heart for the Lord, to leave with you,
that when any offer anything in Men`'s Meetings,
which contradicts the ancient rules and divine precepts
settled amongst us in the heavenly power,
they contradict the very counsel of God, and it is but an offering of strange fire,
which God never commanded, neither will accept, and so they bring death over themselves,
kindle strange fire in the meeting, dazzle the minds of Friends,
and are hinderers of the work and service of truth.

[.signed-section-signature]
Thomas Wilson

[.the-end]
THE END
