[#life-travels, short="The Life and Travels of Thomas Wilson"]
== A Brief Account of the Life and Travels of Thomas Wilson.

I was born in Soulby, in the parish of Daker, and county of Cumberland;
my parents names were Edward and Ann Wilson,
who brought me up in the profession of the church of England,
and taught me the catechism, having been sprinkled or baptized, in my infancy,
according to the manner of that church.
While I was a youth,
I had great hungerings and thirstings in my heart after righteousness,
and the true knowledge of the living God, and of his Son, Jesus Christ,
in which time I went with great diligence to hear the priests; and when there,
did carefully mind what was spoken:
and when I heard of a priest that was noted for a good man,
and preached two sermons in one day, I went from our own parish,
after the forenoon sermon, eight miles on foot to hear an afternoon sermon.
The more I sought to hear, my inward hunger and thirst more increased,
so that I was sensible of great poverty of spirit; and in the time of singing psalms,
a thoughtfulness came into my heart, that men should be made holy,
before they could rightly sing to the praise and glory of God.
My mouth was stopped from singing with them, through a godly sorrow that was in my heart,
with secret cries and humble prayers to the living Lord God of heaven and earth,
for the knowledge of the way of salvation;
but being yet in the wilderness of men`'s doctrines, creeds, articles, and outward forms,
I could not find true peace in my conscience, nor see any bright beams of salvation.
In this state I travelled in great godly sorrow, having religious seekings in my heart;
and being weary of the heavy load of sin,
as also the doctrines and worship of men`'s making,
my mind was much inclined to dispute about religion
with all sorts of professors that I met with,
yet still could not meet with peace of conscience.
But many texts of holy Scripture were opened to my understanding, so that I began to see,
what was not of faith, was sin, even in points of worship,
and pretended service to the great God,
remembering the saying of our blessed Lord and Saviour Jesus Christ,
to the scribes and pharisees, formerly, "`You hypocrites,
well did Esaias prophecy of you, saying.
This people draws nigh unto me with their mouth, and honors me with their lips;
but their heart is far from me.
But in vain they do worship me, teaching for doctrines the commandments of men.`"

Thus was I made sensible, that too many of the doctrines of the church,
wherein I was educated, were precepts of men`'s making,
and that our blessed Lord and heavenly Saviour had said to the woman of Samaria,
at Jacob`'s well, "`the hour comes, and now is,
when the true worshippers shall worship the Father in Spirit and in Truth;
for the Father seeks such to worship him.
God is a spirit, and they that worship him, must worship him in Spirit and in Truth.`"
This worship, in the renewings of the Holy Ghost, and not in the oldness of the letter,
I greatly longed to know, but could not find it,
neither could any priest I conversed with, tell me how or where to find it.
But after long travail of spirit and great concern of soul,
the Lord was graciously pleased to make me sensible, that what was to be known of God,
was manifested in man;
about which time I went into an evening meeting of the people called Quakers,
with strong desires in my mind to the Lord,
that if it was the true way of salvation which they preached,
I might have some inward feeling and testimony thereof,
by the blessed word in my own heart.
After sitting some time in silence, a Friend began to speak,
directing and exhorting to an inward waiting upon the Lord in faith,
to receive power from him over every unclean thought;
by which heavenly power they might glorify and praise the holy name of the Lord,
through the ability of his own free gift.

This, I understood to be his holy word of grace,
which the true apostles of our dear Lord and blessed Saviour, Jesus Christ, preached,
and turned the minds of people unto, and then I felt my soul much in love therewith;
and smiting upon my breast, said in my heart, this is what I greatly lacked; that is,
power against every vain thought, and idle word, being things that troubled me.
The Lord`'s power arose in the meeting, and fell mightily upon me,
to the breaking and tendering of my heart, and a glorious time it was,
as the mighty day of the Lord; so that great fear and trembling seized me,
insomuch that the table whereon I leaned, was shaken.
Thus being sensible in some measure of the glorious name and power of the Lord Jesus,
I was full of inward cries, to this effect; O Lord! create in me a clean heart;
for I saw the old one was not clean, and that I had been kissing the letter,
but not the Son, as advised by the holy Scripture, which says, "`Kiss the Son,
lest he be angry,`" etc.

Now was a time of the Lord`'s fierce anger because of sin;
he showed me all things that ever I had done, and condemned the evil;
so that I was made willing to love and dwell under his righteous judgments,
being truly convinced it was the way to come unto the mercy seat.
Then it was upon my mind, that I must cease from all the doctrines of men, will-worship,
hearing the priests, and repeating their sermons,
which I had delighted in and was in the practice of, as religious duties;
it being made plain to me, that I should turn from them,
and mind the gift which was in me, and sit down among Friends in their silent meetings,
to wait upon the Lord in retiredness of mind,
for his heavenly teachings and holy leadings.
In the performance of this inward, divine, and heavenly worship,
the great power of God did wonderfully break in among us,
and many young people were convinced of the inward work of God,
and turned to the Lord with all their hearts.
The meeting, in general, became very tender and heavenly-minded,
and Friends had great love one to another,
the heart-melting power of the Lord being much felt and inwardly revealed,
when no words were spoken by either man or woman.
In this state we travelled in the silence of all flesh,
in which times the Lord often renewed our strength in the inward man,
so that we knew and experienced what the apostle exhorted the primitive Christians unto,
even Christ to dwell in us by faith.
The renewings of the Holy Ghost increased, and were shed on us abundantly in our meeting,
whereby some were so filled,
that they were concerned to declare and preach the things of the kingdom of God,
and what he had done for their souls.

One of the first that came forth in prayer to the Lord, was William Greenup,
and I was the next, that came forth there in testimony,
which was in very great fear and much trembling.
The word of the Lord, in and through me, was as a devouring fire,
burning against all sin and iniquity;
and the Lord made us cry aloud to turn people from all vain worships, to the living God,
who is a holy Spirit.
The precious life of Jesus broke in wonderfully among us,
so that we felt drawings to visit other meetings in the country,
wherein the Lord`'s heavenly power was plentifully enjoyed among us,
and several were convinced of the truth, who turned to the Lord with all their hearts,
and joined with Friends; particularly in our own meeting, whereby it was enlarged.
I was often very much affected in feeling the love and
power of God break through the whole meeting,
and many such heavenly meetings we had, and the word of the testimony,
in the Lord`'s ministers increased among us.
I then found further drawings to other counties,
and visited the meetings of Friends in Lancashire and Westmoreland.

In the year 1682, it was upon me from the Lord, to visit Friends in some parts of Ireland.
I took shipping at Workington, and landed at Dublin, where I was altogether a stranger;
and after I had stayed a meeting among Friends,
they inquired which way I intended to go; I told them,
I had a desire to see some Friends who dwelt between the west and north.
A Friend answered, he did not think there was such a place inhabited by Friends,
or to that effect, but if I would see Friends, I must go north or south,
which brought great trouble upon my mind, and I became very low in spirit,
questioning in myself,
whether I was not mistaken in that which I thought was
the Lord`'s powerful opening in my heart,
showing me both the place and people, and wherein I thought I had the mind of Christ,
in the holy vision of life.
The cries of my heart were great unto the Lord in secret, why I was mistaken;
but after some time, a living hope sprung in me, that I was not mistaken,
and that the Friends lay as I had seen.

A Friend, named Abraham Fuller, spoke kindly to me, and said,
he lived near the middle of Ireland, and if I would go with him,
we might get a meeting among Friends at Edenderry,
and I had much peace in going with him.
We had a blessed meeting with Friends at Edenderry;
and next day travelling towards Lehinche, where he dwelt,
he asked me if I understood the compass; I told him no,
and that I had not seen any compass in all my life, but the one in the ship,
wherein I came to Dublin.
He was then very cheerful, and lovingly said, he remembered that I had said in Dublin,
I would go between the west and north, which now, said he, I see is true,
for we go even as you then said; at which I was truly thankful to the Lord,
who never fails to be gracious, and his blessed word is infallible.
For then I, like Samuel,
knew it was the word of the Lord that called me into his work and service,
and showed me these things before I went from home.
We came cheerfully on our way, until we got to Lehinche, and from there to the Moat,
where we had a blessed heavenly meeting; so to Mountmellick, and had a meeting there,
and from there to James Hutchinson`'s,
and from there to the Province Meeting at Castledermot.

This Province Meeting was large, and several able Friends in the ministry were there.
I was very low in my mind, and did not go up into the gallery,
but sat down a little within the door, and many people came in,
so that the place about where I sat was much thronged;
it being a time that the rabble sort of people were very rude.
Several such were there that day, and I being under great exercise of spirit,
the powerful word of the Lord filled my heart,
so I stood up and preached the Gospel in the
demonstration of the spirit and power that was upon me.
The rude rabble were astonished and became very quiet,
and the Lord`'s heavenly power did shine forth gloriously,
under a weighty sense whereof the meeting held and concluded.
This meeting brought me into acquaintance with
Friends to whom I had before been a stranger,
notwithstanding I understood afterwards they were afraid, when I stood up,
that my appearance would have been hurtful, but it proved otherwise,
to their great satisfaction.

After this meeting, I went into the county of Wexford and visited Friends,
having several blessed heavenly meetings with them in that county;
they were a lowly plain people.
From there I came into the county of Wicklow; and some little time after,
the motion of life in me for travelling ceased, and I dared go no further,
but returned back into the county of Wexford, and wrought harvest work at Lamb`'s-town,
where Robert Cuppage, a Friend in the ministry dwelt,
who had a concern to visit Friends in Munster,
and would have taken me with him for a companion.
But I told him I dared not go,
because the Lord had taken away the motion of life from me,
and I must wait upon the Lord, to know his blessed will and good time;
so I stayed at my work.

In a little time after, came James Dickinson, a young man from Cumberland,
to visit Friends, with intention to go into Munster,
and then the Lord was pleased to open my way to go with him.
We being both very young, travelled together in true brotherly love, great humility,
and godly fear;
and the blessed heavenly power of the Lord did often tender our hearts in meetings,
as also the hearts of many Friends, and we had a prosperous journey in the will of God:
so I saw it was good to wait the Lord`'s time in all things;
and having travelled through Leinster and Munster, James Dickinson went northward,
but I was afraid of running before my true guide,
because they who run and are not sent of God,
can neither profit the people nor themselves.
So I stayed at work in the city of Waterford, about sixteen weeks,
and went from there to Dublin, and attended the Half-year`'s Meeting there,
which was large and very good;
then took shipping and landed at Liverpool with my former companion, James Dickinson;
and though it was now a time of great persecution of Friends in England,
it pleased the Lord to give us a peaceable and
prosperous journey through the meetings of Friends,
in our way to Cumberland.

In a little time after, with my dear companion, James Dickinson,
I visited Friends in the two counties of Cumberland and Westmoreland.
At Kendal, some persons came to break up our meeting, and began to pull out Friends,
and in a very rude manner took out my companion.
Then the word of the Lord came mightily upon me,
and I was made bold to stand up and preach the everlasting Gospel among them;
the holy power of the Lord came mightily over the hearts of Friends,
and even the opposers were made quiet a considerable time;
but after I had stood about an hour, they came and pulled me to the door.
I asked for my hat, and they said, give him his hat,
he does well to put it off when he preaches.
And after they had asked me many questions, I asked one of them,
whether he was a believer in Jesus Christ or not?
He said he was, and also in the apostles`' doctrine.
Then I told him he never read that either Christ or his apostles,
entered into any religious assemblies, to disturb them as he did us, except Paul,
before he knew the Lord Jesus,
for which sin he afterward calls himself the chief of sinners.
I bade him consider, and sat down in the meeting, all being very still,
and in a little time James Dickinson kneeled down to prayer;
the Lord`'s heavenly power came over all, and the meeting ended sweetly.

In the year 1684, my said companion and I travelled through Lancashire and Cheshire,
into Wales, and had many blessed meetings, both in North and South Wales,
in all which no informer disturbed us, until we came to Redstone in Pembrokeshire,
where a constable, with a wicked informer, and several other persons came;
and as I preached the word of the Lord to the people, the informer laid rude hands on me,
and pulled me away.
I spoke to him mildly, desiring him to let me speak a few words, and he did so.
The constable, and those with him, also sat down and stayed about an hour,
in which time I preached the way of salvation to them all; after which,
James Dickinson kneeled down to prayer,
and the informer came to pull him up from his knees, but could not,
he being in fervent prayer to the Lord,
so the meeting ended in a sweet feeling of the Lord`'s glorious presence:
thanksgiving be unto Him that lives forever and ever.
Amen.

The informer came and laid his hands on me next, saying I must go with him.
I asked, where?
He said, before a justice.
I asked for his warrant; he answered, he was a commissioned officer,
and I had nothing to do to ask him for a warrant.
Friends told him it was but a civil question, at which he was very angry,
but no man laid hands on us to take us away, so we fell into some friendly discourse.
I was very pleasant and easy in spirit; and walking to and fro in discourse,
one of the company said I smiled, which they admired at, we being likely to go to prison.
I answered, that I came in the true love of the Lord Jesus Christ to visit them,
and had nothing but love and good will to them all; and turning to the informer,
said to him, if you was in a journey as we are,
and any man should ask you to go with him before a justice of the peace,
without the king`'s justice`'s warrant, you would think it below you, as a man, to go.
This being mildly spoken to him, he gave a sudden answer, saying, to be sure he would.
Then said I, consider our case; whereupon perceiving he had overshot himself,
he rode away and left us.

We having appointed a meeting to be held next day at Haverfordwest,
went there that night, and next morning to the meeting; wherein, after a little time,
the glorious power of the Lord did shine, and that text of holy Scripture came before me:
"`Then said these men, we shall not find any occasion against this Daniel,
except we find it against him concerning the law of his God.`"
After they had prevailed with King Darius to sign a decree,
whereby Daniel might be ensnared in performing his duty to his God,
this righteous man declined not his duty, through fear of suffering, but was very bold,
as well as innocent, as appears in the tenth verse of the same chapter: "`Now,
when Daniel knew that the writing was signed, he went into his house,
and his windows being open in his chamber, toward Jerusalem, he kneeled upon his knees,
three times a day, and prayed and gave thanks before his God, as he did previously.`"

This subject was preached to the people, as our case, men having nothing against us,
but for worshipping the Lord God of Daniel in his holy Spirit,
according to the institution of our blessed Lord and Saviour,
above sixteen hundred years ago; and that in this glorious Gospel time,
we are to be very diligent and faithful to the Lord, to keep up our religious meetings,
even in stormy times of persecution, referring to the example of Daniel,
who was blessed of the Lord for his faithfulness; boldly declaring and affirming,
that the Lord, whom we serve in the Gospel of his Son,
will reward all his faithful children and people,
instancing many proofs out of the holy Scriptures.
The aforesaid informer and several priests, whereof his brother was one,
together with some of the town officers, being outside of the house,
and hearing these Gospel truths preached, were very sober, and stayed a great while.
Then some of them said, let us pull them out of their meeting; but others said, no,
by no means; for if this be the Quakers`' doctrine, it is good and sound,
we never heard the like, let them alone; so went away,
and our meeting ended in prayer and thanksgiving to the great Lord of heaven and earth,
who is worthy forever and ever.

This informer fined Friends very much, but the Lord, by one means or other,
prevented their goods from being taken away; and lastly,
by the death of King Charles IL After this,
no informer troubled us in any meeting where I came,
though we had many meetings to visit, as in Glamorganshire, Herefordshire, Radnorshire,
Montgomeryshire, Shropshire, and Flintshire;
in all which meetings we had blessed sweet waterings and a confirming ministry,
and Friends were glad in that the God of peace had rebuked the storm in those parts.
My companion and I parted for the service sake; he went into Ireland,
and I travelled northward, and had a prosperous journey through Cheshire, Lancashire,
and Westmoreland.

Friends at Great Strickland, not being permitted to meet in their usual meeting place,
met in the highway before the meetinghouse door,
and the officers came while I was preaching the word of the Lord, but were very sober,
and did not break up our meeting.
From there I came home, where my mother and family, with Friends and neighbors,
were very glad to see me safely returned, in that stormy time.

After some stay at my outward employ about home,
I found drawings to visit Friends in Northumberland, Bishopric, and Yorkshire;
and had many blessed meetings mostly peaceable,
though the storm of persecution was not yet fully ended.
I went into Warwickshire, Oxfordshire, and Oxford city,
where I heard the scholars had been rude, and much abused Friends.
I went into that city on a first-day morning, in great fear and humility,
being a stranger to all Friends there, and sat down in a corner of the meetinghouse.
Friends sat by the sides of the house, and left the middle empty for the rabble.
We having sat a little time, a Friend began to speak,
and had spoken but a very few words before the scholars came in, in such abundance,
that I supposed they filled the middle part of the house.
The Friend sat down as soon as they came in, and the meeting being in silence,
they began to talk one to another, and spy out who would preach;
and seeing me like a traveller, said, that one in the corner, looking rudely upon me;
thus talking one to another for some time.
The word of the Lord was strong in my heart to preach unto them; but I was first to say,
sit down, young men, we shall be glad of your company so long as you are civil;
which done, they all sat down, and began to listen earnestly what I would say.
I preached the way to the kingdom of heaven, declaring it to be by Jesus Christ,
through regeneration and being born again;
and that blessed Jesus taught this doctrine to Nicodemus, "`Except a man be born again,
he cannot see the kingdom of God.`"
And though he was a master or teacher in Israel, yet being carnally minded,
he could not understand these things;
neither can any carnal-minded men now know the things of God,
for no man knows the Father but the Son, and he to whomsoever the Son will reveal him.
So those who preach against revelation,
preach against the true knowledge of the living God, and life eternal;
for our blessed Lord said, "`This is life eternal,
that they might know you the only true God, and Jesus Christ whom you have sent.`"
And this knowledge is in and by the spirit and holy
gift of his saving grace that brings salvation;
and so I went on preaching as it opened in me;--the scholars went away quietly,
and the meeting ended in prayer to Almighty God.

I went from Oxford to Highwiccomb, and so to the city of London, where I stayed some time,
and had many blessed meetings among Friends.
Several of these were held in the streets,
where Friends were kept out of their meeting houses,
and the Lord`'s holy word was preached boldly in that city.
Friends were then a lowly, humble-minded people,
and the honor of the blessed truth was precious to many.

From there I travelled through some counties, in the way to Norwich,
and had meetings among Friends, and an honest Friend with me, Samuel Waldenfield,
who had the way of salvation to preach in the powerful word of life.
We had very large meetings in Norwich,
there being great openness in the people of that city and many parts of the county,
to receive the testimony of the Lord`'s truth, it being a time of convincement;
from there I travelled to Lincolnshire and Yorkshire, and so northward to Cumberland,
and had blessed meetings among Friends.

After I had settled some time to my outward employ in Cumberland,
I went to meetings up and down in that county,
and was moved of the Lord to visit Friends in Wales, and from there to Bristol,
having a very sincere companion, William Greenup.
We travelled together in great unity, and had many powerful meetings in several places,
the Lord`'s heavenly power did mightily break and tender the hearts of Friends;
and in the city of Bristol,
they said we came in the same power and plainness that those Friends
did who were the first instruments in turning them to God.
It was a time of great humiliation and thankfulness to the Lord,
both in Friends and people, of whom some were convinced, and turned to God.

We went from Bristol into Wales again, and stayed some time at Haverfordwest,
and had many large and heavenly meetings; and then took shipping together for Ireland,
and came to Dublin, where we were gladly received by Friends.
After having travelled through all, or most parts of that nation where Friends inhabited,
and had many blessed meetings, we came to the Half-year`'s Meeting at Dublin,
where we parted.
William went home, and I travelled again into the north part of Ireland,
and stayed there some time among Friends; so took shipping at Carrickfergus,
and landed in Scotland, and had some blessed heavenly meetings among Friends there.
From there I returned to Cumberland, the place of my nativity,
where my relations and Friends were glad to see me well,
on my return from so long a journey, of about nine months time.
I stayed here some time working at my outward employment,
and was also at many blessed meetings in this county.

After this stay in Cumberland, I went with my dear companion, James Dickinson,
into the west of England, in the Lord`'s work.
We had a precious journey, being filled with the holy Spirit, to preach the word of God;
and meetings were now very large, many people came to seek after the Lord`'s truth,
and much desired to hear the word; the strong wind of persecution being ceased,
so that there was a great calm.
We had glorious meetings,
the Lord`'s tendering heart-melting power greatly breaking through them.
We visited the meetings in Somersetshire, Devonshire, Cornwall, and to the Land`'s End,
so returned northward in great peace,
and visited Friends in Gloucestershire and Worcestershire, and parted at Coventry.
James went to London, but I travelled northward, and visited many meetings,
both of the north and east counties; so went to London, in the power of the holy Spirit,
and preached the Gospel of the kingdom of heaven.
From there I returned to Cumberland, where I stayed diligently at work for a time,
then took my leave of Friends, in order to enter upon a long journey.

I first went into Westmoreland, and then into Lancashire, Cheshire,
North and South Wales, and so to Bristol, Somersetshire, Dorsetshire, Hampshire, Surrey,
and London, in which city I met with my dear companion, James Dickinson,
and was exceeding glad to see him.
We both having had a great exercise in our minds to visit the Lord`'s people in America;
and having certificates on that account from the
respective Monthly Meetings to which we belonged,
laid our intentions before Friends at London, for their concurrence,
which they received very kindly, and approved of,
believing that the Lord had called us to preach his Gospel in that part of the world.
But the times seemed likely to be very dangerous;
the French being at war against England, had a great fleet at sea,
and while we were in London, the rumor was,
that the French fleet lay about thirty or forty leagues from the Land`'s End of England,
in the way we should pass, which brought a very great concern upon us,
with many inward seekings and supplications to the Lord, that if it was his blessed will,
he might be pleased to preserve us: and being strong in faith,
that it was easy with the Lord God to deliver us, we trusted in his holy power.
I being in deep travail of soul, had an opening from the Lord,
that it was his holy will to deliver us, and we should live to see it, which I believed,
and was humbly thankful to the Lord, and told my dear companion thereof with great joy,
for being nearly united in true love, we could freely open our minds to each other.
He also told me, that being under a travail of soul,
the Lord had showed him that the French fleet would encompass us on both sides,
and also behind, and come very near,
but the Lord would send a great mist and darkness between us and them,
in which we should sail away, and see them no more:
thus we imparted our minds to each other before we left London;
and our openings so agreeing with one another, we were the more confirmed,
that it was of the Lord.
We stayed in this city until the Yearly Meeting, 1691, was over.
A blessed meeting it was, and Friends tender love was towards us,
many ancient Friends being there; particularly William Edmundson from Ireland,
who gave us advice, which we took very kindly,
he having been in America in truth`'s service.

We sailed from London to Gravesend, and had a blessed meeting there,
with the Friends that accompanied us from the city, and then took leave of each other.
We sailed to the Downs, and the master being very kind, we went on shore,
and had some meetings thereabout,
wherein the Lord`'s holy power tendered our hearts together;
and from there we sailed to Plymouth, and went ashore,
where we had some blessed comfortable meetings, and Friends were very glad to see us.

On the 9th day of the fifth month, 1691, we went on board, and sailed to Falmouth,
where all the fleet put in; and at times we had very good meetings,
both Friends and people being very open to hear the truth declared.
After our return aboard the ship, and sailing some time, we met with the French fleet,
which gave us chase, coming up under English colors, within musket shot of us;
then the English putting up their own colors, the French began to fire at them:
the first French ship that came up was very large, and as it is said, had ninety guns;
nigh to which ship were eleven more, and seventy sail behind them,
as some of our company said they counted.
The first ship pursued us, and fired hard, a broadside at every time;
and being come up within musket shot,
the Lord was graciously pleased to hear our prayers,
and sent a great mist and thick darkness, which interposed between us and them,
so that they could not see us, nor we them, any more.
James Dickinson arose from his seat, and took me by the hand, saying,
now I hope the Lord will deliver us, for he had seen all fulfilled,
which the Lord had showed us before we left London.
This was cause of great gladness to me,
who had been under a deep travail of spirit with fasting and prayer to the Lord,
that he who smote his enemies in times past with blindness, might please to do so now,
which the Lord did please to answer,
in a sense whereof our hearts were truly thankful to him: my fasting, praying,
and inward giving of thanks continued three days.

Two ships of our company which escaped came up with us; we were glad to see them;
and the captain of our vessel being a very kind man,
called to those in the other two ships to come aboard his, and have a meeting with us;
which they readily did, and a large and good meeting we had,
giving glory to the Lord`'s holy name for his great deliverance.

We sailed on our way rejoicing, continuing healthy and well until we landed at Barbados,
which was on the 24th of the sixth month, 1691.
Here we found a great sickness among the people, but Friends were glad to see us.
The first meeting we had, I was at the burial of a noted Friend,
where we sounded forth the word of the Lord, a multitude of people being there,
both white and black, and the Lord`'s holy word powerfully reached,
and broke many of their hearts into great tenderness; the blacks stood astonished,
with tears running down their cheeks and naked breasts.
We stayed above two months in that island, in all which time the sickness raged,
yet we had many large and precious meetings, to which there was a great flocking,
the people being very much humbled by the sickness,
and several received the truth and joined with Friends.
Being clear in our spirits of that island,
we parted with Friends in great love and sweetness.

On the 22nd of the eighth month, we took shipping for New York,
and arrived there the 23d of the ninth month next;
and though we had a great storm in our passage, which lasted ten days,
the Lord`'s good hand preserved us.
The captain was very much down in his mind,
and under indisposition of body in the time of our voyage; and said to me, we,
meaning himself and the crew, should die like rotten sheep.
I said, no, captain, do not fear, for I saw that the ship would go safe in;
and after some further discourse, he hugged me in his arms, and seemed to rejoice.
We accordingly arrived at New York, and had a meeting there,
and from there went to Long Island, where we had several good meetings with Friends.
Then the word of the Lord in me, was, hasten,
hasten to visit my great people in Philadelphia; so we went forward,
having some good meetings in our way there.

When we came to Philadelphia,
there was a great division raised among Friends by George Keith:
we preached the Lord Jesus powerfully among them, and had some labor tending to peace.
My companion had it often upon him to warn them all to keep more inward to the Lord.
We stayed some time there, and visited Friends in that province,
having many precious meetings among them, some of which were kept without doors,
for lack of room, and there was a great flocking to hear the truth declared,
although it was winter time.
We went from there into Maryland, and visited Friends on the Eastern and Western Shore,
and travelled to Virginia, and had many good and comfortable meetings among them;
the Lord`'s good presence accompanying us from time to time,
and we found a tender humble people there.

We went from Virginia towards North Carolina, where the floods were so great,
that we could not travel on horseback, but waded barefoot through swamps and waters:
Friends and others were exceedingly glad to see us,
not having had any visit by a travelling Friend in the ministry for several years before.
We had good service among them,
for the Lord`'s heavenly power wonderfully supported us
under our difficulties and hard travel,
the country being so full of wild creatures,
that wolves would come and howl about the houses in the night time.
After having had many good and heavenly meetings with Friends there,
we took leave of them, and returned through the wilderness to Virginia,
and so travelled up James river, having meetings as we went, until we came to Curies,
where we had some meetings to satisfaction among Friends and other people.

We went from Curies, through the woods, to Black creek, where we had appointed a meeting;
and none having been there before, the sheriff, with some officers, came to break it up.
James Dickinson being then declaring, the sheriff asked him,
from whom he had his commission to preach?
James answered to this effect; I have my commission from the great God,
unto whom you and I must give an account.
At which words the sheriff seemed much astonished;
and after they had some further discourse, the sheriff swore,
for which James reproved him, and said, the sheriff should not swear.
He answered, I know I should not swear, seeming then very mild; and said,
we had a gracious king and queen, and they had given us our liberty.
I then stood up, and asked the sheriff a question; inasmuch, as he had said,
we had a gracious king and queen,who had given us our liberty, which was true,
by what law would the sheriff persecute us?
He then turned about and went away; whereupon James Dickinson spoke aloud, saying,
let the sheriff answer the question; hut instead of doing this,
he took the man of the house a little way off,
and sent him back to bid us go off his land.
I told him, we did not come there without his leave,
and both he and the people might know we had not broken the king`'s law,
but were there upon a religious account,
and if they would have a little patience and hear what we had to say for the Lord,
we would go peaceably away.
Most of the people stayed, and we had a heavenly meeting among them;
several were convinced, and in a short time after a meetinghouse was built,
and a meeting settled there, which I think is kept there still.

After the said meeting at Black creek, one Charles Fleming,
who had not been at any of our meetings before, being reached by the truth,
kindly invited us to lodge with him, which we did; and from his house,
travelled towards Maryland, having company a little part of the first day`'s journey,
and were then left in the woods; and after travelling all day,
we sat down in the dusk of the evening, to eat some bread and cheese.
My mare went out of my hand, and in a little time I perceived she had found water,
at which I was very glad;
and I think I never drank any wine more sweet and pleasant to me, than that water was.

We lodged that night in the woods, and as soon as the day broke,
set forward on our journey through the woods, northward; and as we were travelling,
met with two men, one of whom being an ancient comely man,
kindly invited us to his house, where we stayed two nights, and had a meeting,
though he was an elder among the Presbyterians.
He also lent us his boat to go over Potomack river,
and that night we lodged at a poor man`'s house, and had no bed to lie on.
As we were sitting by his fire, he told us,
that George Fox and John Burnyeat had travelled in those parts,
and had meetings on both sides the river, and many were convinced,
but several of them fell away.
We got next day over Patuxent river, into Maryland,
and had many blessed meetings among Friends on both sides of the bay;
and being clear of those parts, went towards the lower counties of Pennsylvania,
and so to the Yearly Meeting at Salem, in West Jersey, which held several days;
the Lord`'s holy power was largely manifested therein,
and Friends were in great love and unity.
From there we went to Philadelphia,
where we found the difference between George Keith and
Friends broken out to an open separation,
he having gathered a company to himself, and set up a separate meeting,
which was cause of great exercise to faithful Friends.
Seeing we did not go to his meeting, he sent us a challenge to dispute;
which we readily complied with, and had a meeting with him and his party,
a great many faithful Friends accompanying us.
We sat a while in silence to hear his charges against Friends, namely:
that some of them were not sound in faith, doctrine, and principle.
He did not prove it, nor permit Friends to answer him, but went on in railing;
we made our observation, though we said nothing,
which raised a great desire in him and his abettors,
to have another meeting with me and my companion; which we readily agreed to,
provided some faithful Friends went along with us, to bear witness,
for I knew that the like separate spirit, which had appeared in England,
was a lying spirit.

Some time after having several Friends along with us,
we met again with the said George Keith, and the chief of his abettors;
and being quietly set to hear what he had to say,
he advanced his former charge against Friends, as being unsound in faith and doctrine;
to which I answered, saying, no error in faith, doctrine, or principle of particular men,
was a sufficient reason for him to set up a separate meeting.
He opposed me; then I asked liberty to be heard, and told him to this effect;
if he and his company were sound in faith and doctrine, and men of God,
they should have kept up their testimony for the Lord in the meeting;
and if there must have been a separation,
such unsound men would have gone away from Friends, as those did formerly,
of whom John said, "`They went out from us, but they were not of us;
for if they had been of us, they would no doubt have continued with us,
but they went out, that they might be made manifest, that they were not all of us.`"
I also asked them, where ever they knew faithful Friends in England leave their meeting,
and set up a separate meeting.
Thus we left the dispute at that time,
and went to visit the meetings of Friends in the Welch tract, or plantation,
and in the country; so returned again to Philadelphia, and had a third meeting,
with Keith and his party, which was very large.
I told them, they were gone from the Lord in an airy flourish, and the wit of man,
and had set up a separate meeting;
but in a little time the Sun of Righteousness would shine among them,
and drive away the misty doctrines of men, and that they, the separatists,
should dwindle, die away, and come to nothing,
except such who were most honest towards God, who should return to truth and Friends;
which, in a little time, was fulfilled in both respects.

Leaving Friends at Philadelphia, we went into the country to a meeting,
to which George Keith came, and asked me where we would be on the first-day, saying,
that he had appointed a meeting to be next first-day at Crosswicks.
Finding freedom, I went there,
but my companion found drawings from the Lord to go to Philadelphia,
and be at the meeting there that first-day, to which George Keith came,
contrary to his appointment, and leaving his separate meeting,
met with Friends in their large meetinghouse, and preached fawningly,
as though he and James Dickinson were in unity.
After he had done, James stood up in great authority in the Lord`'s power,
and confuted George`'s doctrine and practice, setting truth over him and his party,
and opened the mystery of salvation to the people to their great satisfaction.
George Keith went away in great wrath; and the people, who were not Friends, being many,
cried aloud, give way, and let the devil come out,
for the little black man from England has got the day.
After which, George called his party together to their meetinghouse,
and told them that James Dickinson had never appeared against him till that day,
but had then made himself equal with Thomas Wilson, meaning in opposition to him.

After this meeting, James Dickinson came to me at Crosswicks,
from which we travelled through Jersey, and to the Yearly Meeting at Flushing, on Long:
Island, which was a large and blessed meeting.
Having visited Friends in that island, and had good service for the Lord among them,
we travelled through the country, till we came to Rhode Island,
and were at the Yearly Meeting there, which was very large and heavenly,
the Lord`'s tendering power being mightily over it.
We travelled from there through New England, to Boston;
and after having had some service for the Lord there,
we travelled into the eastern parts of the country;
and the Indian war being very hot at Hampton, and thereabout,
many of the people were gone into garrisons; and it was upon us to go to a garrison,
which we did, and had a meeting near it at a Friend`'s house.
After this meeting, we returned back to Salem, where Friends were glad to see us safe,
several having been murdered on the road, and some that same day.
We went from there to Boston again,
and inquired if any ship was bound from there to Barbados; and there being one,
but not fully ready, we went to Rhode Island again,
and had several good meetings among Friends there;
so parting with them in great love and tenderness, we returned to Boston.

On the 17th of the sixth month, 1692, we took shipping at Boston, for Barbados;
and after we had been about two or three days at sea, the ship being new, sprung a leak,
and part of our lading being tar, some ran out of the barrels into the hold,
and our pumps clogged, so that our situation looked very dangerous.
I stripped myself to work at the pump,
and James went with the captain to search the hold,
where they found a tree nail hole that the carpenter had left open;
and after they got it stopped, through the Lord`'s great mercy,
we arrived safe at Barbados.
Some time before we went in, the weather became thick and dark,
continuing so all the forenoon; but about twelve of the clock, the sun broke out,
and our sailors got an observation; immediately after which the mist came over again,
and the darkness was so great,
that although there was a privateer which had laid several days in that latitude,
we escaped him and got well in;
so that we saw the same hand which preserved us in our first going there,
by bringing in a thick mist over us, had again preserved us in like manner;
which was cause of great joy to us and Friends on the island, who gladly received us.

We landed at Barbados on the 2nd day of the eighth month, 1692, where we stayed some time,
and visited Friends meetings thoroughly, and had good service for the Lord.
The sickness which was in the island at our first coming, still continuing,
the people were very much humbled,
and their exercise further increased by a plot
the blacks had laid to murder the white people,
which was discovered in the following manner.

A certain man had a black servant whom he respected,
and the servant was so well pleased with his master, that he said to himself,
my master is a very good man--great pity to kill my master; and being overheard,
some gave information thereof to his master; upon which he had him apprehended,
and examined before the governor, but he denied all.
However, they sent him to prison,
and set a private watch to see if any of the blacks would come to speak with him,
which several did privately, and charged him not to confess,
for a great many hundreds would come and rescue him out of prison,
and also go on with the massacre.
This occasioned him to be brought again before the governor,
and then he confessed the whole plot; which was, to kill all the white men at night,
and to seize the fort, shipping, horses and arms; but being thus discovered,
many of the blacks were taken and hung up in gibbets alive, till they died.

Being clear of Barbados, we went from there to Antigua, where we stayed some time,
and had several large meetings among the people;
the Lord`'s power did so prevail over them, that several were convinced of the truth,
and afterwards became faithful Friends.
We passed from there to the Island of Nevis; and when near it, had a consultation,
whether to go in on the north or south side thereof;
and by the favorable direction of divine providence, for our preservation,
we went in on the south side,
where we heard that a French privateer which lay on the north side of the island,
had taken a vessel about the same time.
We stayed several weeks on that island, and had many meetings therein,
and had good service for the Lord.
The inhabitants had been visited with a mortal distemper, of which many were taken away,
as they told us.
There had been four priests on the island before; but when we came,
there was but one of them living: he was a great drunkard and a swearer;
and when the inhabitants came to our meetings, and were reached by the Lord`'s power,
so that they confessed to the truth, this wicked priest was very angry,
and told them he would come and dispute with us at our meeting on the first-day.
This being spread through the island,
many of the inhabitants of great note came to the meeting,
though the priest did not come, but went to the governor to inform him against us.
We had a large meeting, in which the everlasting Gospel was proclaimed among them,
and all were warned to repent of their sins, and turn to the light of Jesus Christ.
Many hearts were reached; one that was a justice of the peace, confessed to the truth;
and also wrote to the governor on our behalf.

Being clear of this island, our names were put up at a public place, as the law required,
with notice of our going off the island,
and certificates written and carried by a Friend to the governor to be signed by him;
but he would not sign them, for he had been much enraged by the priest,
and threatened that he would put us in the fort and see us before we should depart.
So we took horses, and went with the master of the ship,
with whom we had taken our passage, to the governor`'s house;
he appeared very angry with us, and said,
we were spies come to spy out the strength of the island.
We told him, we were no spies, but true men; and to satisfy him,
we showed him a pass which had the secretary`'s seal to it,
which we had obtained at our coming out of England;
wherein all governors and officers were commanded to let us pass.
When he saw the broad seal, his countenance fell,
and he asked us why we had not showed it to him before.
We replied, we had not showed it then but for his satisfaction, that we were not spies,
but true men; and further told him, we came in the love of God to visit our Friends,
and the inhabitants of the island.
Then he signed the certificate,
and called for a bottle of wine to drink with the captain and us,
but we would not drink any with him,
for we were deeply bowed under the sense of God`'s goodness to us,
who had not only drawn us into his service, but also had made way for us,
and wrought our deliverance.
In the latitude of Bermudas, a tornado came, which is a storm of wind,
and our topsails being set, laid the vessel on one side like a log of wood,
she remaining so for some time; in which season,
the glory of the Lord did so shine upon us, that the fear of death was taken away,
and our hearts were filled with the joy of God`'s salvation.

Being clear of our service for the Lord in America, we took shipping from Nevis homeward,
and in about six weeks landed in the highlands of Scotland;
and travelled from there into Cumberland, where we had some meetings,
and Friends greatly rejoiced at seeing us,
they having heard that we were taken by the French.
From hence we travelled up to the Yearly Meeting at London,
having some meetings in our way there.
We had a very blessed Yearly Meeting, Friends being in great love and unity,
and much rejoiced to see us, as we did to see them;
and there is great thankfulness in my soul to the Lord
for his manifold favors and preservations,
both by sea and land.

After the Yearly Meeting at London was over, I went,
accompanied by Thomas Story through Oxfordshire, and so to Bristol,
where we met with Thomas Camm and Joseph Bains.
Thomas Camm being inclined to stay some time longer in Bristol,
Joseph Bains went with us into Wiltshire, and some western parts,
where we had many good and blessed meetings;
but at Warminster the people were contending with Friends,
and we had two large meetings among them,
wherein the Lord`'s tendering power broke in among them, so that many were reached,
and went away well satisfied.
After having spent some time in those parts, we returned again to Bristol,
and Thomas Story and I went northward for Cumberland,
having many good meetings in our way there.
I stayed at home a while, following my outward employment,
saving that now and then I visited Friends in that county.

In the fall of the year 1694, I had some drawings to visit Friends in Ireland,
and William Greenup having the like concern,
we travelled together through part of Scotland, having service there,
took shipping at Port Patrick, and landed at Dunnaghadee, in the north of Ireland.
We visited Friends generally in that nation,
and also had several meetings among other people.
We had a prosperous journey,
the Lord`'s blessed presence and power accompanying us in his service;
and the wars being newly over, there was a great openness in the people,
and tenderness among Friends.

About the beginning of the second month, 1695, I returned from Ireland,
and landed at Whitehaven in Cumberland, where I made but little stay at home,
having a concern to be at the Yearly Meeting in Wales,
to be held at Dolobran--I travelled pretty directly there.
In this meeting the Lord`'s good presence and power was enjoyed,
to Friends comfort and refreshment.
After it was over, I travelled to Bristol, and stayed some meetings there,
and from there to London, and was at the Yearly Meeting;
soon after which I returned again into the north; and in the fall of the year,
married Mary, the daughter of Thomas Bewley of Woodhall, in Cumberland,
who proved a true help-mate to me.
After my said marriage,
I found freedom in the truth to remove with my wife into Ireland to dwell, which I did,
and settled near Edenderry, in the King`'s county.

Some time after my removal into Ireland,
I found drawings from the Lord to visit Friends in England;
and in the fall of the year 1696, took shipping from Dublin, and landed at Holyhead,
and travelling through part of Wales, and into Worcestershire and Gloucestershire,
to Bristol and London, I visited the meetings of Friends thoroughly.
From there I went into Surrey and Sussex, and visited the meetings of Friends there;
so returned again to London, where I had further service for the Lord;
and from there passed northward through Hertfordshire, Huntingdonshire, Lincolnshire,
and into Yorkshire, travelling along the sea coast, as far as Newcastle,
and from there across the country to Carlisle.
I had many very refreshing seasons in this journey among Friends;
and after having visited Friends meetings in Cumberland, I went to Whitehaven,
in order to take shipping; but in the time of my waiting for a passage,
had a very large meeting there out of doors,
in which the word of life was declared among the people, and the meeting ended well.
I landed in Ireland in the twelfth month, and returned home, where I found my wife well,
which was a great satisfaction to me.

Soon after, I found drawings to visit Friends in this nation, which I did accordingly,
and had meetings in many places among other people, where none had been before,
nor any meetings of Friends settled, and many were convinced,
of whom some received the truth in the love of it, and continued faithful thereunto.

From the year 1697 to 1713, I often visited Friends in this nation, and also in England;
within which space, I was seven times at the Yearly Meeting in London,
the Lord`'s good power accompanying me in his service.

I having had it upon me from the Lord for a
considerable time to visit Friends in America again,
my dear ancient friend and companion, James Dickinson, signified to me by a letter,
that he had a like concern, whereof I was truly glad,
for we had often travelled together in great love, unity, and sweetness.
We met in Dublin, and took shipping for America in the tenth month, 1713.
The name of the captain of the vessel was Richard Kelsey, of Whitehaven in Cumberland.

We made our voyage north about,
and after I had seen the captain`'s diligent care and
good conduct in his ship among his servants,
and those on board, it drew my heart towards him in much love,
and gave me encouragement to take the freedom of
having some religious discourse with him,
wherein I found he aimed at justice and equity, so that my love increased towards him.
He being frequent in praying,
we entered into discourse of the substantial part of prayer; I told him,
we could not pray at all times in words, knowing our own insufficiency,
but waited for the assistance of the holy Spirit to help us, and guide our understanding,
having regard to what the apostle said,
"`I will pray with the spirit and with the
understanding also,`" which might be inwardly performed,
although no words were outwardly spoken.
To which he readily assented, and told us,
we might keep our meetings in the great cabin at any time when they did not keep theirs,
and said, he thought we did pray inwardly.
Though we had a storm in this passage for near a month together,
yet the captain`'s prudent management of the ship,
and showing himself so very respectful to us all along,
and the good conversation we had together, made our voyage much the pleasanter.

On a seventh-day of the week at night,
the captain told us we should find the soundings next day,
which we did accordingly about noon; and he told us, that if the gale stood,
we should reach the cape that evening.
Sailing on till near night, we were within about seven or eight fathom water;
but night coming on, he wisely stood out to the sea,
and in a short time we got into Lynhaven bay,
having been nine weeks in our passage from the sight of Ireland,
and after a little stay in that harbor we sailed
on until we came into Rappahannock river,
and from there went ashore at Queen-Ann`'s town,
where we parted with our kind captain in great love:
he would have us take some of our provision, and gave us much loving counsel,
which we accepted kindly.

At Queen-Ann`'s town, we hired horses to York river,
and next day took boat to the Western Shore;
from which we contentedly took our travel on foot into the woods, having our saddles,
saddle-bags, and great coats upon our shoulders; and after a little time,
seeing a man at a distance, riding towards us, James Dickinson said,
who knows but yonder man is coming to help us.
When he came up, the man knew James, and cheerfully said,
I had best alight and take your things upon my horse; which we kindly accepted,
and he went along with us to James Bates`' house, who received us very kindly,
his wife having been convinced by James Dickinson, and was a faithful Friend.
It being their weekly meeting day, we went along with them,
and had a good time with the few Friends there.

We travelled from there through Virginia to North Carolina,
having many good meetings among Friends and other people,
many being glad to see us again in that country.
We found a hopeful generation of young people,
who received the testimony of truth with gladness;
and having visited their meetings thoroughly, and had a good time among them,
we returned again into Virginia, and visited Friends up James`' river,
and so by Black creek, towards Maryland.
Having had good service for the Lord in those parts,
and several good meetings in our way,
we visited Friends on the Western Shore of Maryland,
and found great openness both among them and other people;
from which we went over the bay, and visited Friends on the Eastern Shore,
and in the lower counties of Pennsylvania, and so to Salem in West Jersey,
the Lord`'s good presence attending us from meeting to meeting.
We stayed the Yearly Meeting at Salem, which was very large,
and the Lord`'s power eminently manifested therein,
and the doctrine of truth was largely opened to the people.
Having visited Friends on the east side of Delaware river, we went over to Philadelphia,
and visited the meetings of Friends in Pennsylvania, which were very large,
many sober people flocking to them,
unto whom the testimony of truth flowed forth in the word of life,
to the opening of the understandings of many.

From Pennsylvania we crossed over Delaware river again,
and travelled through the country to Shrewsbury; and in our way there,
a Baptist preacher came up to us, and directing his speech to me, said,
he would ask me a question; I bid him, say on; then said he, my question is,
"`what is the ordination and qualification of a true minister of Jesus Christ?`"
To which I answered, that the apostle says, "`As every man has received the gift,
even so minister the same one to another, as good stewards of the manifold grace of God.
If any man speak, let him speak as the oracles of God; if any man minister,
let him do it, as of the ability which God gives:
that God in all things may be glorified, through Jesus Christ.`"
I further said mildly to him,
you may see that the ability of a true minister is in the divine gift.
Then he said, I have another question to ask, which is this,
"`can any man who has this divine gift positively deny
the command of our Lord Jesus Christ?`"
To which I replied, that no man, who was faithful to this holy gift,
dared deny the commands of our Lord Jesus Christ.
But, said he, you do.
Then, said I, how comes you to charge me thus?
What have you seen by me, to charge me with denying the commands of Jesus Christ?
I know, said he, you are a Quaker;
and that all the Quakers deny the positive command of Jesus Christ.
I answered, you have charged boldly, now you must prove in what we deny them.
He said, you deny water baptism,
which Jesus Christ commanded to be an ordinance in his church to the end of the world.
I told him, he must prove his assertion,
for I did not understand that ever Jesus Christ gave any command to his ministers,
to baptize in elementary water.
I desired him again to prove what he had asserted.
He began to repeat many Scriptures, quoting chapter and verse.
I patiently heard him until he had gone on a great while;
and seeing he had wrested the Scriptures, I told him he must now make a full stop,
until the company came up, for my companion had a bible in his pocket,
and we would read the texts which he had mentioned, and any other he had yet to name.
They soon came up to us, and the bible being called for,
it was given into the hands of a young man,
who was desired to read all those texts which the Baptist had
urged to prove water baptism to be a command of Jesus Christ,
and a standing ordinance in the church.
After he had named many texts, they were read to him one by one;
but finding no text to make good his charge,
I told him he had wronged the Scripture in adding thereto, which, said I, is dangerous,
for we read in the Revelations, 22:18, "`If any man shall add unto these things,
God shall add unto him the plagues that are written in this book.`"
After which I opened unto him the true baptism of Jesus Christ,
which is with the Holy Ghost and with fire; as John said. Matt. 3:2.
and we parted very friendly.
He came to the meeting next day, and was silent.

From Shrewsbury, we travelled to Woodbridge and New York, and from there to Long Island,
where we stayed the Yearly Meeting, which was a large and blessed meeting.
From there we went by water to Rhode Island,
and was at their Yearly Meeting in the fourth month,
wherein the power and the glory of the Lord did very much appear,
and the universal love of God was held forth to the satisfaction of the people.

We went from there to Taunton, where no Friends meeting was settled,
nor do we know that any had ever been there before.
To this meeting several sober people came,
who were open to receive the testimony of the truth, and some were convinced,
since which a meeting is settled there.
Then we went to Dartmouth, where James left me, and went to the island of Nantucket,
but we met again at Sandwich, and travelled together through the country to Boston,
where we had some service for the Lord, both among Friends and other people.

From Boston we went to Lynn and Salem, so to the eastern parts of New England,
as far as Dover; and after having visited Friends there, returned by way of Boston,
to the Yearly Meeting at Providence, where we had good service for truth.
We travelled through the country until we came to Rhode Island again,
having had several meetings in our way, and found great openness in several places.
After some stay in Rhode Island, and having had several precious meetings among them,
we parted from Friends in great love and tenderness,
and returned by water to Long Island,
where we made some stay in visiting Friends`' meetings,
and found a great openness among them.

From Long Island we went to New York, where we had a large and blessed meeting;
the people who were not Friends, confessed to the truth.
We returned by Woodbridge, and through Jersey to Pennsylvania;
and after having some meetings among Friends, went to the Yearly Meeting at Burlington,
which was very large, and held several days,
in which meeting the Lord`'s blessed power was richly manifested.
Then we went to Philadelphia, and from there, by way of Newcastle,
to the Yearly Meeting at Choptank, on the Eastern Shore of Maryland, in the eighth month,
which was very large,
many people besides Friends flocking to it from several parts of the country,
and the doctrine of truth was largely opened to them.
After this meeting, we went into the lower counties of Pennsylvania,
and had several meetings among Friends, in which we were greatly comforted;
so returned again to Philadelphia, and spent some time in and about that city,
having good service for the Lord, and had a farewell meeting with Friends at Chester;
and then hastened to Oxford on the Eastern Shore of Maryland,
in order to take shipping for England.

Soon after we came to Oxford, we agreed with the master of a vessel for our passage,
the ship being bound for Liverpool,
but told him we had a desire to stay the first-day meeting.
He said, if he did not fire a gun, we might stay; and a little before the meeting began,
he fired a gun, which gave us warning to hasten aboard,
although it was contrary to our freedom,
not being clear in our minds to leave the meeting, so we went on board.
They set sail,
but made little way that day and we soon perceived that
as the master of the ship had endeavored to cross us,
the Lord crossed him, for there arose a great storm that night,
which continued several days, in which time the ship sprung a leak, which daunted them;
yet taking some courage again, they kept to sea, but the leak increased so fast,
that they altered their course, and stood in again,
and with some difficulty got to an anchor in Lynhaven bay,
which brought a fresh engagement upon us of
thankfulness to the Lord for so signal a preservation.
Here the master concluded to unlade, that he might stop the leak,
and told us we might go on shore and see our friends.

We hired a boat, sailed up the river, and went ashore at the house of a widow woman,
a Presbyterian, who received us kindly, and said she had heard of us,
and that the New Testament made much for us.
After we had eaten and drank, we would have paid her, but she would take nothing from us.
She shoved us a little on our way, and we parted with her in a friendly manner,
and that night got to a Friend`'s house, and afterwards among Friends in Virginia.
My companion and Robert Jordan, took boat and went aboard the ship,
and brought off our things; the master then showed himself very respectful, and said,
if we thought fit to come again, we should be very welcome,
and if not we might use our freedom.

We travelled to and fro in Virginia,
and through the country until we came to the Western Shore of Maryland,
having many blessed meetings.
Friends being very glad to see us, and thankful to the Lord for our late preservation.
We also went over the bay,
and had a meeting with Friends at the place where the
captain would not allow us to stay before.
After this meeting, we were free in our spirits to return,
being thankful to God for his manifold preservations;
and in a little time after took shipping in another vessel,
and landed at Cork in Ireland, where we stayed a meeting on the sixth-day of the week;
and then went to Clougheen: next day got to James Hutchinson`'s,
where we lodged that night, and rode next morning to Mountmellick,
where the Province Meeting for Leinster was then held.
We went into the meeting.
Friends being gathered before we came, and the power of truth broke in upon the meeting,
whereby Friends hearts were greatly tendered,
under a sense of the Lord`'s mercy in preserving us,
not knowing anything of our being landed, until we came there.

Here I parted with my dear friend and companion, James Dickinson;
and as we had travelled together in great love and unity, we parted in the same.
He went to Dublin, in order to take shipping for Cumberland,
and I returned home to my dear wife and family,
being truly thankful that the Lord had brought us together again.

I stayed a little time at home, and then our Half-year`'s Meeting coming on at Dublin,
I went there, and from there to London,
in the company of Friends appointed to attend the service of the Yearly Meeting there.
We had several good meetings in our way,
and the Lord`'s power was eminently manifested in the Yearly Meeting.
When it was over, I left the city, and returned northward by way of Coventry,
and so for Ireland, and found my dear wife and children well, to my great satisfaction;
and after some stay about home, visited Friends`' meetings up and down in the nation,
as I found drawings in the love of truth.

In the year 1721, I found a concern upon my spirit,
to go for England in the service of truth; and after our Half-year`'s meeting in Dublin,
took shipping in company with John Barcroft,
and several other Friends intending to the Yearly Meeting at London.
After being two days at sea, the ship struck often on the sand in the night time,
so that we seemed in great danger of being lost;
but through the favor of divine providence were preserved, and in the morning,
the tide being out, the ship lay aground, and we got out our horses,
and went ashore in Wales, from which we rode seventeen miles to Chester,
and from there to White-church, where one of our company parted with us.
The rest of us travelled to Wolverhampton,
and were at the meeting on the first-day of the week,
and the next day we all met at Dudley, at a burial.
I, with one other of our company, went to Storbridge,
and we all met again at the Quarterly Meeting at Bromsgrove in Worcestershire;
and travelled together to Oster, and so to Evesham and Sheepstown,
at each of which two last places we had a meeting, and then went to London,
and were at the Yearly Meeting, which was large and peaceable.
After it was over, I stayed a little time in that city, and had some service for the Lord;
and so departed in company with John Barcroft, and travelled through Buckinghamshire,
Berkshire, and Wiltshire, and from there to Bath, and so to Bristol,
in which city we stayed some time, and had several very precious meetings.
I went from Bristol into some parts of Gloucestershire, and when clear,
returned to Bristol, and had some further service for the Lord; and my dear friend,
John Barcroft, being indisposed and feeble of body,
I left him among his kind friends at Bristol,
having a constraint upon me to fulfill the service that was before me.
I travelled westward, as far as the Land`'s End in Cornwall,
having many very blessed meetings through the country.
I visited Cornwall thoroughly, and was greatly comforted with Friends there,
and found great openness among the people in several places.
I returned by Plymouth, Exeter, Bridgport, Pool,
and from there by the sea coast until I came to Dover,
having many refreshing meetings as I travelled through that country,
Samuel Hopwood being with me; we went from Dover to Canterbury,
and by Rochester to London.

I stayed in and about the city of London several weeks,
the Lord`'s presence and power attending me in his work;
then travelled into Hertfordshire, and had many good meetings greatly to my satisfaction.
I returned to London, where I had again some comfortable meetings;
and being clear of that city, parted with Friends in great love and sweetness,
and travelled through Essex to Colchester, and from there to Ipswich and Woodbridge,
and through Suffolk into Norfolk, having many meetings,
Isaac Pickerel of London accompanying me.
We had two very large meetings at Norwich, greatly to edification,
the word of eternal life being freely preached, whereby many hearts were tendered;
so travelled through the country, until we came to Lynn,
having many good meetings in our way there.
I was very glad to meet with several,
who were convinced when I formerly travelled through that county.
At Lynn I parted with Isaac Pickerel, and went northward, through Lincolnshire,
Michael Williams going along with me to several meetings.
I passed from there into Yorkshire, visiting Friends meetings;
and made some stay at York, and had service for the Lord.
Then I crossed the country, and went to the Yearly Meeting in Wales,
which was held at Glanneedlass, having several meetings as I passed along.
In this Yearly Meeting, the Lord`'s power and love was richly manifested,
and I was greatly comforted among Friends; after which I went to Holyhead,
and took shipping for Ireland, and in the third month, 1722, returned home,
being truly thankful to the Lord,
who had supported and enabled me by his divine power to answer his holy requirings.

I stayed about home, sometimes visiting Friends`' meetings that were near;
and in the year 1724, went to the Half-year`'s Meeting at Dublin, in the third month,
where I was greatly comforted in the feeling of that divine life and power,
which is the crown and glory of our meetings.
After this meeting I returned home, and growing infirm,
went little abroad to distant meetings; but in the ninth month following,
Friends of Leinster kept the Province Meeting at Edenderry, to which I went,
and the Lord`'s power was richly manifested,
and the affairs of truth managed in great love and sweetness; John Fothergill,
from England, being there, had good service for the Lord.

Now I rejoice in that I have served the Lord in my day;
and as I have labored to promote the truth in my generation,
I feel great peace from the Lord, flowing in my soul;
and am thankful that I have been made willing to serve him.
My dear wife, being a woman that truly fears God,
has freely given me up to answer the requirings of truth,
and I hope she will have a share in that reward and peace,
whereof the Lord has given me the earnest.
I have deeply travelled both in body and spirit for the promotion of truth in the earth,
in a general way, so I have also often besought the Lord,
that he would be pleased to reach effectually to my own children in particular,
that they may be faithful witnesses for him in their generation.

[.asterism]
'''

Our dear friend, Thomas Wilson, being taken ill of body,
about the 18th day of the eleventh month, in the year 1724,
continued weakly for several months, in which time he uttered many weighty expressions;
and at several times was concerned in fervent prayer to the Lord,
for the young and rising generation,
that they might be faithful witnesses for the truth in their day.
He was freely resigned to the will of God,
yet desired of the Lord if he had no further service for him,
to remove him out of his pain, which, at times, was very great.

When he was a little easy, he often spoke of the things of God,
and was very much concerned that Friends should live agreeably to the doctrine of Christ,
and that the good order established among us by our faithful elders,
might be kept up and maintained,
and that all differences and disorders should be kept out of the church; and said,
if Friends kept the ancient path, and observed the Lord`'s rules,
they would be a blessed people, expressing his satisfaction,
that in all nations where he travelled,
he had been careful not to join with any that were for false liberty,
or laying waste the testimony of truth, which the Lord had called his people to bear.

One evening, several Friends sitting with him,
he was very sweetly and prophetically opened in words to this effect;
that a great harvest-day was coming over the nations, and that the Lord was fitting,
and would fit many, and send them into the harvest; but said,
he hoped in a little time to be gathered to the generations of the just,
that were gone before;
and was comforted to feel that Friends were inward with the Lord in their spirits,
expressing how near truth made Friends one to another in the beginning,
and that he was glad of the nearness and unity among Friends now,
desiring it might continue and increase.

At a time he was asked, if he would have anything to wet his mouth;
to which he replied to this effect; the Lord has taken away all my pain,
and given me the bread of life, and the water of life, and quenched my thirst,
which has been great, the will of the Lord be done;
and fervently prayed to the Lord for his people, especially the youth,
that he would be pleased to incline their hearts to follow him in the way of truth:
and soon after said to this effect,
if the youth of this meeting and nation incline their hearts to the Lord above all,
he will make them a shining people; but if they do not, he will cast them off.

And again said, the Lord`'s goodness fills my heart,
which gives me the evidence and assurance of my everlasting peace in his kingdom,
with my ancient Friends that are gone before me,
with whom I had sweet comfort in the work of the Gospel.
Those who touch the Lord`'s work, and are not of clean hands, will not prosper.
Notwithstanding our said friend had been eminently attended with the power of truth,
and had great service many ways, he would speak very humbly of himself,
ascribing all the honor to the Lord.
And at a certain time he said to this effect:
although the Lord has made use of me at times to be serviceable in his hand,
what I trust in, is the mercy of God in Jesus Christ.
To Friends sitting by him, he said, the Lord visited me in my young years,
and I felt his power, which has been with me all along,
and I am assured he will never leave me, which is my comfort.

He also often expressed his desire, that Friends might dwell in humility, and keep low,
for that to his sorrow, he had seen many who grew high, come to ruin,
both themselves and posterity, and their places left desolate.

Near his conclusion, he often desired the Lord would give him an easy passage,
which was granted, being also preserved sensible to the last;
so passed away without sigh or groan, as if he had been going to sleep,
on the 20th day of the third month, 1725.
He was buried the 22nd of the same, accompanied by a great number of Friends and others,
where Friends had a good opportunity to bear testimony to that divine power,
whereby he was raised up to be a faithful witness for the truth, in his generation.
And though his removal be a great loss to his family in particular,
and the church in general, it is no doubt his everlasting gain.
