== Testimonies Concerning Thomas Wilson.

[.chapter-subtitle--blurb]
The Testimony of Mary Wilson, Concerning her Dear Husband--Deceased.

Since it has pleased the Lord to remove from me my dear husband by death,
there has often been a concern upon my mind, to give forth a testimony concerning him:
and having good cause to remember the time of our first acquaintance,
is an inducement to give some account thereof.

I well remember, when he was come up to the state of a man,
how earnestly he desired the knowledge of the true God;
in which time he went from one place to another,
among the members of the church of England,
to hear what their priests could tell him of the way of salvation;
for his soul was in need of a Saviour,
and great was his hunger after the way of life and righteousness.
In this tossed condition he continued for some time, looking after the teachings of men,
but they proved altogether unprofitable, which was a great trouble to him.

In this condition the Lord was pleased, in his unspeakable love,
to visit his soul with his light, and his invisible power,
by which he was much broken into tenderness.
It was then a time of great humiliation and fear, in which condition,
he came among the despised people, called Quakers;
and although there was then great persecution,
yet he sat down with them in their meetings, in silence,
until it pleased the Lord so to fill his heart with his powerful word,
that he knew the burning thereof, as a holy flame in his soul;
then his mouth was first opened in public prayer and thanksgiving to the Lord;
and afterwards to declare the day of the Lord, that was dawned,
and to sound the everlasting Gospel, which was glad tidings to many poor benighted souls.

I may safely say, concerning him, that when he was sensible,
the Lord had revealed his Son in him,
and that a necessity was laid upon him to preach the Gospel,
he did not consult with flesh and blood, but gave up to the heavenly vision,
and was willing to spend the flower and prime of his days in the service of truth,
which he did, in many years travel, and labored much in the work of the ministry,
in England, Ireland, and America, before we married.
In the fortieth year of his age, we took each other in marriage, in Cumberland,
and soon after came into Ireland, and settled pear Edenderry,
he having had some time before, a remarkable sight of that place,
of which at times he would speak; and we had reason to believe it was our place,
for the Lord blessed us together,
and we had great comfort that it was our lot to
settle among such honest tender-hearted Friends,
to whom we were nearly united.

After we were settled, he was often engaged to travel in truth`'s service; and I may say,
from a certain sense that rests upon my heart,
that the more he gave up to the work he was called unto, the more we were blessed.
Although it was pleasant to me to have the company of so good a husband,
yet it was more solid satisfaction to me to give him up
to answer what the Lord might require of him;
and.
to the praise of God, I was made a sharer with him,
in the sweetness of that heavenly love and life, with which his heart was often filled,
and streamed forth to the comfort of many;
for he was as a cloud that the Lord often filled and caused to be emptied,
to the refreshing of his heritage.
My soul, with many more, has great occasion to bow in deep thankfulness to the Lord,
for the many refreshing showers, that we have been favored with,
and give him the praise thereof, who is worthy forever.

And further, I have to say, concerning my dear husband,
that he was a loving and kind husband, a tender father to his children,
and one that was laborious in the creation, and provided plentifully for his family,
open-hearted to his Friends, and beloved in the neighborhood, by such as knew him.
He often looked with a pitiful eye towards the poor of all sorts,
and administered to the needs of many; he delighted in justice and hated wrong things;
and although the Lord blessed him many ways, yet was not his mind lifted up thereby,
but he continued to the end a humble-minded man.

He was often sorely afflicted in body,
yet frequently travelled to visit Friends in much pain.
In his last journey, in England, which was about ten months,
he endured much bodily weakness, which continued upon him to his end,
for he went no more abroad, only to our own meeting,
and twice to the Half-year`'s Meeting in Dublin.
Although his pain was great at times, yet he went to meetings as long as he was able.
It was often afflicting to me, to think of being left behind; but what shall I say?
the Lord has done it.
He has given, and taken away; may my soul be so preserved,
in a living sense of his goodness, that I may praise his name while I live,
and be fitted for my final change, and lay down my head in peace,
is what my soul most desires.

The Lord has brought my mind into quietness and contentment with my condition,
steadfastly believing, that he has removed my dear husband in his mercy and favor,
and received his soul into his everlasting kingdom.
I shall conclude this testimony, with fervent desires unto the Lord God Almighty,
that he may, for his work`'s sake,
favor his church and people with a plentiful spring of a living ministry,
and touch the tongues of many of our youth, with a live coal from his holy altar,
that many may be willing to run his errand, and be serviceable in his hand,
as were many of the generation, whom he has removed from us.

[.signed-section-signature]
Mary Wilson

[.blurb]
=== The Testimony of Thomas Wilson`'s Children, Concerning their Dear Deceased Father.

We find ourselves engaged to give this testimony concerning our dear father,
whom the Lord has been pleased to remove from us,
having no small share in the loss of him, who was a tender and affectionate parent to us.
We can truly say,
his concern and care was very great for our growth and preservation in the blessed truth,
and that we might be preserved out of hurtful things; and in a particular manner,
that as we grew in years we might grow in that sense and knowledge of the holy truth,
which we are sure was precious to him.
He was often concerned in a solid,
tender frame of spirit to advise and instruct us
to seek inwardly to know the Lord for ourselves,
and the work of truth in our own hearts,
that would lead us to walk blamelessly and in great humility before him; saying,
that was the way to obtain the blessing.
As he was thus concerned for our good, we are sensible his fervent desires and prayers,
were secretly to the Lord on our account,
that he might be pleased to bless us with an increase
of true wisdom and knowledge in the holy truth;
and we have good cause to believe, that the Lord was graciously pleased in some degree,
to hear and answer bis requests,
in that he has in tender mercy visited our souls with a sense of his divine goodness,
which we fervently desire may increase in and amongst us.

We have great reason, with thankful hearts to bless the Lord on his account,
who made him so great a blessing to us; and not to us only,
but to many more who had a sensible knowledge of him,
and of his diligent care and counsel, that greatly tended to the good of souls; which,
in the love of God, so prevailed in his heart,
that he was made willing to spend and be spent in that service whereunto he was called,
being a faithful laborer in God`'s vineyard,
that truth and righteousness might increase on the earth;
not accounting any fading and transitory enjoyment too
dear to part with for Christ and the Gospel`'s sake.
He was much delighted to see the youth and offspring of
Friends grow up in a living concern for the truth;
and that elders might be good examples and patterns in the church,
which was his care to be found in the practice of.

We could say much more concerning him, but rather choose to be brief,
referring to other testimonies given, with respect to his labors, travels,
and services for the truth; and shall conclude this our testimony, with sincere desires,
that the Lord may so favor us, through his infinite goodness and divine assistance,
that we may thereby be enabled to run the race that is set before us,
so as to obtain the blessing while here,
and the crown of eternal life that is laid up for the righteous,
when time to us shall be no more.

[.signed-section-signature]
Thomas Wilson, Benjamin Wilson

[.signed-section-context-close]
Thornwell, the 1st of the Third month, 1727.

[.blurb]
=== James Dickinson`'s Testimony, Concerning his Friend and Companion, in the Work of the Gospel, Thomas Wilson--Deceased:

Being a testimony to the sufficiency of the Lord`'s power, and the work thereof,
as it is revealed in the hearts of the children of men,
in this as well as in former ages,
unto all who have their minds turned to the light of the Lord Jesus Christ,
so as to believe and walk therein.
These come to have fellowship one with another,
and know the blood of Jesus Christ to cleanse them from unrighteousness,
and are fitted for the service of God; one of which,
was this my dear friend and companion, Thomas Wilson.

The first time I was acquainted with him, was in the year 1682,
when he had the motion of the Lord`'s power upon him to
preach the everlasting Gospel in the nation of England.
He being at our Week-day Meeting at Pardsey,
his mouth was opened in a powerful testimony, to the tendering of many hearts,
and the meeting was brought under a deep baptism of the one spirit into one body,
and drank into one spirit; after which, he soon took shipping for Ireland,
and I having a concern upon me to go into that nation, hastened after him,
where we found it our place to travel together.
The power of the Lord was wonderfully with him, and made him as a cloud full of rain,
carried by the breath of the Almighty, to water the ground.
He had great service while I was with him, and several were convinced by him.

In the year 1683, he visited several counties in the north of England,
it being a time of great persecution,
and the Lord`'s power was wonderfully manifested for our help and preservation.
Some officers came to Kendal,
where Thomas was then declaring the way of life and salvation,
in the mighty power of God, so that the testimony of truth was set over all;
and though they pulled him out of the door, yet had not power to take him away with them,
but let him return in again,
and we kept the meeting in the authority of the Lord`'s power,
until we found freedom to conclude it in a sense of the love of God,
with thanksgiving unto him.

In the year 1684, we travelled together through many counties in England,
and through Wales; in which journey he had great service,
the Lord made him as a flame of fire against sin and wickedness,
and often as a cloud full of rain, to comfort the afflicted.
We met with no informer in this journey, till we came into South-Wales, at Redstone,
where they endeavored to break up our meeting, and could not; but, as we heard afterward,
the Friends of that meeting were very largely fined,
though the distress was prevented by means of moderate justices,
after the death of King Charles II.

The said informer came also to Haverford-West, with a justice to assist him,
but the power of the Lord was so eminently with Thomas, in his testimony,
that the justice said, if these be the Quakers, I never heard the like, let them alone.
In the time of this his journey, many were convinced, and turned to the Lord`'s teaching.
He also travelled in the year 1688, through the south and west parts of England,
wherein the Lord supported him by his heavenly power,
still adding a blessing to his labors.

In the year 1691, we entered upon our long voyage to America,
taking shipping at London for Barbados,
it being a time of war between France and England.
It was showed him, we should meet with the French fleet, which we did;
and it was an exercise to us, but our cries and tears being poured forth to the Lord,
he stretched out his arm for our help, and wonderfully delivered us,
by sending a great fog, or mist,
which blinded the eyes of our enemies,--they
took all the fleet except the ship we were in,
and two others.
My companion had been exercised three days in prayer and fasting,
that we might be preserved,
and the Lord heard his prayers and restrained the hands of wicked men;
so that all those on board were made to confess it was a miraculous deliverance;
and even in the time of trial, we felt the Lord`'s living presence wonderfully with us,
to the melting of our hearts, and strengthening our faith,
in the sufficiency of his power, that is over all.
After which, on a first-day of the week,
the company of the other two ships came aboard the ship we were in,
and we had a large meeting,
wherein the everlasting Gospel of life and salvation was declared amongst them,
and they were made to acknowledge it was the truth.

When we came into the latitude of Barbados, we met with another trial,
in being chased by a man of war, but our eye was to the Lord:
the company concluded to fight, and made preparation for it,
having their places ordered them where they should be; but the captain,
knowing it was matter of conscience to us not to fight, was civil,
and bade us go to the doctor if we pleased; at which the passengers were very angry,
saying, we deserved to be shot to death.
We told them, Christ`'s kingdom is not of this world,
and therefore his servants cannot fight.
But seeing the captain was so kind as to give us liberty of choosing our places,
we would be on the quarter-deck with him,
which greatly confounded those who were so much against us,
and gave us an opportunity to set the testimony of truth over them.
It proved to be an English man of war.

We landed in Barbados the 24th of the sixth month,
where my companion had great service for the Lord,
many hearts being tendered under his testimony, and several convinced.
His labors were also great in New England, Rhode Island, Long Island,
East and West Jersey, Pennsylvania, Maryland, Virginia, Carolina, Antigua, and Nevis,
where many were convinced by him.
In some of these places he passed through many perils, by sea and land,
lodging out in the woods in winter season; and the greatest of all, was false brethren,
but the Lord`'s power supported him over all.

When we were clear of America, we took shipping at Nevis, the 26th of the twelfth month,
and landed at the highlands of Scotland, the 15th of the second month, 1693,
and from there returned into Cumberland, being filled with thankfulness to the Lord,
for his wonderful deliverances; and though we went forth weeping, bearing precious seed,
we returned rejoicing, with sheaves in our bosoms.

We afterwards travelled together up to London,
where we met with Friends from most parts of the nation, who were glad to see us,
and the Lord`'s power was still made manifest for our help in his service;
blessed be his holy name forever.
We being sensible, that without Christ we could do nothing, he wrought all for us,
and in us, and strengthened our faith in the sufficiency of his power: in which faith,
this my said friend lived, and went through great tribulation,
and I doubt not is entered into rest.
Our fellowship was great, and the Lord made us one, both in tribulation and joy,
being bound up together in the bond of love.

In the year 1713, we took our second voyage together for America,
and the Lord made way for us, both inwardly and outwardly,
and preserved us near to himself, and one to another, we having nothing in our eye,
but the honor of his name, and good of mankind.
I know there was not anything more delightful to my dear companion,
than to be under the influence of God`'s holy Spirit, wherewith he was often filled,
not only for his own good, but the good of others,
he having a dispensation of the everlasting Gospel committed to him of God,
which he preached freely, and it was his care to keep it without charge.
Though he had a large gift, beyond many, yet was glad of the least child,
who spoke from the motion of God`'s spirit,
he having learned to cast down his crown at the feet of the Lamb,
for whose exaltation he was given up to spend and be spent.
He had much service in this last visit in America,
and was greatly comforted in seeing the fruit of his former labors,
and those who had been convinced by him, walking in the light of the Lord Jesus Christ.

I might say much more of my own knowledge,
concerning his faithful and diligent labors in the work of the Gospel,
of which a small account is given in his Journal, yet what I have said,
is not to attribute anything to man, but to the Lord`'s power,
which wrought effectually in him, and whereof he was a faithful witness,
to whom be glory forever. Amen.

[.signed-section-signature]
James Dickinson

[.blurb]
=== The Testimony of Friends in Ireland, from their National Half-year`'s Meeting, held in Dublin, from the 8th to the 12th of the Third month, 1726, Concerning that Worthy Elder and Eminent Minister in the Church of Christ, Thomas Wilson--Deceased.

It has pleased Almighty God, the fountain of all mercies,
from whom every good and perfect gift comes, in the riches of his love,
not only to gather his church and people,
but to bless and favor them with many peculiar blessings, and particularly in raising up,
gifting and qualifying many for the public ministry,
and in the power and demonstration of the holy Spirit,
sent them forth to declare the way of life and salvation,
whereby they became instrumental to turn many to righteousness,
and for the building up and settling his church in the most holy faith,
to their comfort and edification.
Of the number of these our dear deceased friend was none of the least,
whom the Lord was pleased to send into this nation, to preach the everlasting Gospel,
first in the year 1682; and he was several times here in the work of the ministry,
before he came to settle in this nation, which was about the year 1694.
Many of us can say,
from a sensible knowledge we had of his diligent labor
and eminent services in the work of the Gospel,
that he was one, whom the Lord gifted with a large gift in the ministry,
and made him instrumental for convincing many.

His doctrine was sound, plain, powerful, and reaching,
frequently attended with a heavenly sweetness;
and when he had drawings on his spirit to go forth in public service,
he was careful in waiting to know the Lord`'s acceptable time, to which he freely gave up,
preferring truth`'s service before his own worldly concerns;
and when he found his spirit clear of the service he was engaged in,
he was careful to return with what expedition he could.
He was often divinely opened to declare the mysteries of life and salvation,
as also to lay open the mystery of iniquity, and to declare against a false ministry,
and was made skillful in dividing the word aright, and to feed the flock in due season.

His ministry was sharp against the rebellious,
but comfortable and consolating to the mourners in Zion and babes in Christ.
The Lord richly endued him with the spirit of prayer and supplication,
in which he was often drawn forth in great tenderness and
fervency of spirit on behalf of Christ`'s church and people,
and for their offspring in a particular manner; likewise in behalf of kings and rulers,
and men in authority, with mankind in general.

He was a good pattern of plainness and humility,
diligent in attending meetings for the worship of Almighty God,
waiting therein to receive that heavenly power,
which first raised him up in a living ministry,
and was careful not to minister without it;
and though he was an able and eminent minister, chose to give way,
rather than stand in the way of any who had a word from the Lord to speak.
He was zealous for maintaining the ancient rules and discipline
settled in the church in the beginning by our faithful elders,
advising Friends to a diligent observance thereof.

Much more might be said concerning his great services,
and diligent labors in the work of the Gospel for many years, both in Great Britain,
Ireland, and America, which are so well known to many, that we need not enlarge thereon.

And now, though this our dear friend be removed from us, which is cause of sorrow,
considering the church`'s great loss, yet we doubt not but it is his everlasting gain.
We conclude with fervent desires, that the great Lord of the harvest may,
for his work`'s sake, be pleased to continue to his church and people,
a living spring of the ministry, and that many may be made willing to run his errands,
and be serviceable in his hand, as was this our worthy friend,
who departed this life the 20th of the third month, 1725;
aged about seventy-one years--having been a minister about forty-five years.

[.signed-section-closing]
Signed in behalf of our said meeting, by

[.signed-section-signature]
Henry Brookfield, George Rooke, William Brookfield, Jacob Fuller, Thomas Bewley,
Joshua Clibborn, John Barclay, Mungo Bewley, Gregory Russel, Joseph Inman, John Stoddart,
Jonathan Robinson, Edward Barwick, Joseph Gill, John Boles, Richard Sealey,
Abel Strettel, Thomas Ducrett, Solomon Watson, Ralph Stephenson, Samuel Watson,
Nicholas Harris, James Pillar, Bartho Garnett, Thomas Greer, James Hill, Daniel Bewley,
Toby Courtney, Samuel Fuller, John Chrysty.

[.blurb]
=== A Brief Abstract of the Testimonies of Friends of the Three Provinces,Concerning our Deceased friend, Thomas Wilson.

[.blurb]
=== From Ulster Province Meeting.
//I'm not exactly sure if that was the right thing to do

He was profound in heavenly mysteries, yet plain and clear in declaring them;
very skillful and excellent in distinguishing matters of faith and principle,
to general satisfaction of the people, who often greatly flocked to meetings,
where he came.

He labored diligently for the good of souls, yet did not run forwardly into service,
in the will of man,
but duly waited for the arising and movings of the word of life and wisdom,
which was often eminently with him, and manifested through him,
to the affecting and tendering of many hearts, and to the glory of God,
the author and giver of all good gifts.

He frequently visited Friends of this province; and the last visit he made to us,
was as much as ever, in the openings of divine love, life and sweetness in spirit,
to the refreshing and edifying of Friends.

[.blurb]
=== From Leinster Province Meeting.

His travels and labors of love in the Gospel of Christ, were great,
frequently visiting the meetings of Friends in this province,
and also having meetings amongst people, where no Friends`' meetings are settled.
In these labors for the spreading of truth, the Lord`'s power and goodness attended,
and particularly at National and other meetings in the city of Dublin, to which,
at times,
many sober people of other persuasions came to hear the testimony of truth declared,
who have been much affected with tenderness of spirit by his powerful ministry;
and though, at times,
he was awfully concerned in warning to prepare for a time of great mortality approaching,
he yet rejoiced in a sense, that the Lord would lengthen his merciful visitation,
and send plentiful showers of the doctrine of his kingdom
before his judgments brake out upon the inhabitants.

He also declared to this effect,
that the Lord would send his servants into the popish countries to preach the Gospel,
which should prevail and spread in those dark parts of the earth,
though some might seal their testimony with their blood.

He was a nursing father in the church, cherishing the good in all,
particularly the young and weak in the ministry, male or female, who were gifted,
and called thereunto, and rejoiced that the Lord had raised up such,
both in this nation and elsewhere; and though he was an honorable elder,
yet very humble and condescending, as a servant to all; grave and reserved in deportment,
often bowed under exercise of spirit, yet at seasonable times, cheerful, sweet,
and pleasant in conversation, both with Friends and others,
whereby he gained the love and good esteem of many.

Notwithstanding he was an able minister of the Gospel,
he was careful not to travel abroad in that service without the unity of the brethren;
and when he found himself clear, returned speedily to his outward abode,
and was diligent in his lawful vocation of husbandry, for the good of his family,
wherein the Lord blessed his endeavors with prosperity and plenty.

[.blurb]
=== From Munster Province Meeting.

He was a faithful laborer in the Lord`'s harvest,
and travelled much in the service of truth,
being willing to spend and be spent for the Gospel`'s sake;
and the Lord blessed his labor of love,
so that many were convinced and became as seals of his ministry.

He was zealously concerned against undue liberty and wrong things,
that truth`'s testimony might be maintained in the several branches thereof;
that in all things,
Friends might walk agreeably to the doctrine of Christ and his apostles,
keeping in the path of the faithful,
without swerving to the right hand or to the left--being very sensible,
that those wholesome rules and precepts, with which we are favored,
have been given forth in the wisdom of truth.

[.blurb]
=== The Testimony of Friends of Coldbeck Monthly Meeting, in Cumberland, Concerning our Dear Friend, Thomas Wilson--Deceased, Who Was a Member of the Said Meeting for Some Time in his Young Years.

This worthy man,
was one whom it pleased the Lord to call out of the broad way and vanities of the world,
and make acquainted with the way of his blessed unchangeable truth,
after having known many days and nights of mourning and sorrow for mis-spent time,
that it might be redeemed, and that he might be acquainted with his Saviour,
Jesus Christ; who, in due time, appeared by his spirit,
to the opening of his heart and enlarging his understanding in
those things relating to the way of peace and salvation.
As he abode under the cross, it pleased the Almighty to manifest to him,
that he was a chosen vessel or instrument for his service, to preach the Gospel,
and declare unto others what great and good things the Lord had done for his soul.
He gave up in obedience to the Lord`'s requirings,
and being largely endued and qualified by the holy Spirit, became an able minister,
and faithful laborer in the Lord`'s vineyard, sound, powerful, and reaching in doctrine,
with plainness of speech, not glossed with human wisdom,
very zealous and fervent in prayer, greatly to the comfort and edification of the church.
His godly example in life, conversation, great humility and self-denial,
much adorned his ministry.
He travelled often in truth`'s service, both in visiting adjacent meetings,
and other parts of this nation,
from which we have had very good and comfortable accounts of his service,
and reception amongst faithful Friends.

He also travelled in Scotland, Ireland, and many parts of America,
where many were convinced by him, and joined Friends in the profession of truth.
He married a Friend of our meeting, and soon after removed into Ireland,
having prospect of a suitable settlement there, and the unity of Friends therein;
and being preserved in faithfulness to the Lord,
and zealous for the promotion of his truth, he was pleased abundantly to bless him,
both spiritually and temporally.
We understand his service was great in that nation,
and not doubting but accounts thereof will be given by Friends there,
we refer thereto for an account of the remaining part of his life,
not intending to be large on this subject, well knowing that all which can be said,
will add nothing to the happy state of the deceased,
but that the memory of the just may remain amongst the righteous,
and his footsteps be as way-marks to succeeding generations,
is the end of our giving this short testimony concerning our dear and worthy friend.
Signed on behalf, and by order of our Monthly Meeting, held at Wood-hall,
the 20th of the second month, 1726.

Joseph Peacock, William Greenup, Thomas Lamb, John Scott, William Scott, Thomas Scott,
John Sowerby, George Bewley, Robert Gill, Benjamin Bewley, Jacob Nicholson,
Samuel Peacock, John Scott.

[.blurb]
=== An Abstract of a Testimony Given by Friends of Virginia, Concerning Thomas Wilson-- Deceased, to which Somewhat is Since Added by Joseph Jordan, a Friend of that Place, Now in Dublin, the 27th of the Twelfth Month, 1726-7.

Among the many faithful laborers,
whom the great Lord of the heavenly harvest has been pleased to send from far,
with his word and testimony, to visit his people in this colony, our worthy friend,
Thomas Wilson, was one eminently serviceable in his ministerial capacity.
He was instrumental to convince some of the way of truth, and to edify and comfort many,
with the word of the Gospel, which is a word of peace and consolation,
as was very manifest by the preaching of this precious servant of Christ,
in whom it dwelt richly.

Some of us knew him in his first visit to Virginia,
in company of our dear friend and elder, James Dickinson, in the year 1690 or 1691.
Friends here were persecuted, and their meetings sometimes disturbed by ill-disposed men;
and those who entertained a meeting, were liable to a fine,
which frightened some well-minded people;
one of whom had given our said Friends liberty to have a meeting in his house,
but upon the threats of the sheriff, was discouraged, as we understood,
and the meeting was held in an orchard, where a person of note received the truth,
under the powerful testimony borne by our dear friend, Thomas,
to the one necessary and saving baptism, which is the baptism of Christ, by his spirit.
After the meeting ended, this man who had joined in with the visitation of God,
through his servant, took him and his companion to his house,
and kindly entertained them, notwithstanding the law, which was then severe.

Much might be said of this first visit of our dear friend;
but concluding that our friend, James Dickinson,
will be more particular and large in his testimony thereof,
we shall proceed to some account of the last visit Thomas gave us,
which was in the year 1714, when, notwithstanding his advanced age,
he was lively and strong in the word of faith,
and preached it with much power and demonstration,
to our great comfort and encouragement;
and he spake sometimes prophetically in our meetings concerning the prosperity of truth.
After he had put us in mind of the many visits we had
been favored with by ministers sent from Europe,
who had been instrumental to gather and settle meetings in America, he told us,
the Lord would raise up and qualify many amongst ourselves,
to declare the word of his salvation, which is measurably fulfilled.
He also said, that many great men,
and many young men should bow to the truth in our wilderness country;
which we humbly hope will be brought about in time,
and that the church of Christ will increase and be more
and more extensive in this part of the world.

This man of God also assured us, in the word of prophecy,
that way would be made for the spreading of truth in the pope`'s dominions;
and that the feet of many from Great Britain should be turned that way,
some of whom should seal their testimonies with their blood; in declaring which,
and much more, great tenderness appeared in him,
through the virtue and power of the divine anointing,
in which his understanding was very bright.
We have cause to magnify the Lord our God,
for sending this his approved minister amongst us,
and for the many profitable and very memorable opportunities we had with him.
The account of his decease affected our minds with sorrow,
by reason of the church`'s loss, especially in Ireland, where he sojourned,
and where his removal out of this life is doubtless lamented by the faithful,
who had been so often and largely refreshed and edified by his labors of love,
in the gift of the ministry.

To conclude, we have this testimony to bear,
touching the behavior and conversation of our said friend, when with us;
that it was the confirmation of his doctrine,
being the practice of that holy religion he taught, with great sincerity and success.
Spending the time of his sojourning on earth in fear, he was preserved to ancient years;
and having finished his day and testimony, he rests from his labors,
and his works follow him.

Signed on behalf of Friends in Virginia, the 14th of the fifth month, 1726,
by John Porter, Samuel Sebrell, Robert Jordan, John Small, Gerard Robert Ellison,
Nathan Newby.

[.blurb]
=== The Testimony of George Marke, Concerning our Dear Friend, Thomas Wilson--Deceased.

I had some knowledge of him before he was convinced of the blessed truth,
whereof he afterward became an able minister;
in which time of my first acquaintance with him, he was light and airy in conversation,
much given to sporting and jesting,
having an inclination to make people laugh and be merry, as he called it.
But in a little time after, the Lord was pleased to visit him, and break his rest,
giving him a sense of the vanity, and unprofitable way of living,
wherein he then seemed to have a life; and in a short time,
a very great change was wrought in him.
All his mirth was turned into mourning, and his laughter into lamentation;
solitary places became his resort,
and the Lord having in some measure opened his understanding,
he was earnestly concerned to seek for a Saviour,
and zealous in going constantly to hear the priests, and some other professors,
and would bring a great deal of what he had heard home with him, repeating it over,
as if willing to feed a little upon it; which proving like husks,
and not solid food to a seeking languishing soul,
he came gradually to be made sensible by the glimpse of Gospel light,
shining in his own conscience,
that all the performances he could attain to in that state, being empty and fruitless,
brought no lasting peace to him.
In a while he left hearing the priests, and frequented Friends`' meetings; and the Lord,
in his own time, was pleased further to visit him,
whereby he was tendered and broken at times,
and scarcely able to contain himself under the
great exercise of spirit that was upon him.

But the Lord, who had wounded,
was pleased in due season to pour healing oil into his afflicted soul,
comforting and strengthening his inward man,
so that he had a few words sometimes to deliver in the meeting.
His appearance therein was in great dread and fear, and his words piercing,
being attended with a divine authority,
and several were convinced by him in the early time of his ministry:
one instance I may relate.
He was concerned in testimony at the burial of a
Friend belonging to our meeting at Mosedale,
the burying-place being near my house, and four of my servants, not of our persuasion,
who were at work a little distance off, hearing the sound of his voice, left their work,
and drew near to hear him, where they were so reached by his testimony, that,
to the best of my remembrance, they never went any more to hear a priest,
but were all convinced, and came amongst Friends.

He was one whom the Lord was pleased to bring through the furnace of affliction,
and make a chosen vessel for his use and service,
being soon called to travel abroad in the work of the ministry;
so that his outward settlement, or place of abode was little more amongst us;
but this I may say, I believe with many more,
that when it pleased the Lord to cast his lot amongst us,
we partook of his service which the Lord concerned him in, with great satisfaction,
comfort, and confirmation in the blessed truth.

I conclude with my firm persuasion, that he was one of the valiants of Israel,
who has done his day`'s work carefully, and is entered into that rest,
prepared of the Father, for the faithful; and though he is removed,
yet his memory will live amongst us.

[.signed-section-signature]
George Marke

[.signed-section-context-close]
Mosedale, in Cumberland, the 28th of the Third month, 1726.

[.blurb]
=== The Testimony of Thomas Priestman, Concerning his Dear Friend, Thomas Wilson--Deceased.

That the Lord our God, who is the Father of mercies, has in this day, as in former ages,
visited a people with the day-springing from oh high,
is signally manifested and experienced,
and that he fails not to answer the desire and
breathings of that soul which feels its lack of him,
and seeks him in sincerity, however bewildered at times,
not knowing where to find him whom it seeks after, is evident,
by his gracious visitation of this our dear friend, Thomas Wilson, who, I believe,
did sincerely seek after the knowledge of the truth, that he might not be deceived;
and though his exercise of spirit was great,
with strong cries and groans that could not be uttered in words, yet the Lord,
who has said, call upon me in the time of trouble, and I will hear and deliver you,
answered the desire of his long mournful and distressed soul.

I remember one time at a meeting at Woodhall, a Friend there warned the people, and said,
it was a day of visitation to some in that place;
and Thomas Wilson was wonderfully broken in spirit,
until it pleased the Lord to reveal his Son in him,
and give him an understanding of what he should do, which, for a season,
he was unwilling to give up unto; but the Lord`'s power prevailed,
and made him willing to deny himself, and obey the Lord, in declaring the word of life,
as required, and which often flowed through him,
to the refreshing and comforting of the church of Christ, and convincement of several.
Many who had travelled and been afflicted in spirit with him, that he might be preserved,
and brought through to the praise of God, were made glad,
he often having a word in season from the Lord,
to speak in great love and tenderness to tribulated souls,
remembering he had been afflicted, and not comforted for a time.

Much might be said on the behalf of this our friend and brother, of whom.
I had many times a feeling sense while amongst us;
but his works and labors of love for God, and his people, declare aloud for him,
whereby he being dead, yet speaks.
He is fresh in the remembrance of many of us, and the dealings of God with him,
who raised him from a low degree, and made him an able minister of the Gospel,
to turn people to the knowledge and obedience of the truth in themselves.

[.signed-section-signature]
Thomas Priestman

[.signed-section-context-close]
Dearudding, the 20th of the Second month, 1726.
